using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.DdeftWebService.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.DdeftWebService,findAllPtcpntDpositAcntByFileNumber method, Response.
	/// Code Generated by IMS on: 12/20/2018 7:29:47 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISbyFileNumberfindAllPtcpntDpositAcntByFileNumberResponse : VEISEcResponseBase
	{
		[DataMember]
		public VEISbyFileNumberreturnMultipleResponse[] VEISbyFileNumberreturnInfo { get; set; }
	}
	[DataContract]
	public class VEISbyFileNumberreturnMultipleResponse
	{
	}
}
