using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.DdeftWebService.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.DdeftWebService,findAllPtcpntDpositAcntByFileNumber method, Request.
	/// Code Generated by IMS on: 12/20/2018 7:29:47 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISbyFileNumberfindAllPtcpntDpositAcntByFileNumberRequest : VEISEcRequestBase
	{
		[DataMember]
		public Guid RelatedParentId { get; set; }
		[DataMember]
		public string RelatedParentEntityName { get; set; }
		[DataMember]
		public string RelatedParentFieldName { get; set; }
		[DataMember]
		public bool LogTiming { get; set; }
		[DataMember]
		public bool LogSoap { get; set; }
		[DataMember]
		public bool Debug { get; set; }
		[DataMember]
		public LegacyHeaderInfo LegacyServiceHeaderInfo { get; set; }
		[DataMember]
		public string mcs_filenumber { get; set; }
	}
}
