using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.DdeftWebService.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.DdeftWebService,updatePtcpntDpositAcnt method, Response.
	/// Code Generated by IMS on: 12/20/2018 7:39:17 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISupdateParticDepAccupdatePtcpntDpositAcntResponse : VEISEcResponseBase
	{
		[DataMember]
		public VEISupdateParticDepAccreturn VEISupdateParticDepAccreturnInfo { get; set; }
	}
	[DataContract]
	public class VEISupdateParticDepAccreturn
	{
	}
}
