using System; 
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.CpeDrugAdapterServiceV3.CRMOL.Messages
{ 
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.CpeDrugAdapterServiceV3.CRMOL,getDrugInfo method, Response.
	/// Code Generated by IMS on: 5/31/2018 2:05:54 PM
	/// Version: 2018.05.09.05
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISgDIgetDrugInfoResponse : VEISEcResponseBase
    {
		[DataMember]
		public VEISgDICPEDrugAdapterv3getDrugInfoResponse VEISgDICPEDrugAdapterv3getDrugInfoResponseInfo { get; set; }
		[DataMember]
		public bool ExceptionOccured { get; set; } 
	}
	[DataContract]
	public class VEISgDICPEDrugAdapterv3getDrugInfoResponse
	{
		[DataMember]
		public string mcs_textOfReport { get; set; }
		[DataMember]
		public VEISgDIcode VEISgDIcodeInfo { get; set; }
		[DataMember]
		public VEISgDIfault VEISgDIfaultInfo { get; set; }
	}
	[DataContract]
	public enum VEISgDIcode
	{
		SUCCESS,
		ERROR,
	}
	[DataContract]
	public class VEISgDIfault
	{
		[DataMember]
		public bool mcs_essCodeSpecified { get; set; }
		[DataMember]
		public string mcs_essText { get; set; }
		[DataMember]
		public string mcs_code { get; set; }
		[DataMember]
		public string mcs_text { get; set; }
		[DataMember]
		public VEISgDIessCode VEISgDIessCodeInfo { get; set; }
		[DataMember]
		public VEISgDInestedFault VEISgDInestedFaultInfo { get; set; }
	}
	[DataContract]
	public enum VEISgDIessCode
	{
		SUCCESS,
		ERROR,
		WARNING,
		REFUSED,
		ACCEPT,
		REJECT,
		FAIL,
	}
	[DataContract]
	public class VEISgDInestedFault
	{
		[DataMember]
		public bool mcs_essCodeSpecified { get; set; }
		[DataMember]
		public string mcs_essText { get; set; }
		[DataMember]
		public string mcs_code { get; set; }
		[DataMember]
		public string mcs_text { get; set; }
		[DataMember]
		public VEISgDIessCode1 VEISgDIessCode1Info { get; set; }
	}
	[DataContract]
	public enum VEISgDIessCode1
	{
		SUCCESS,
		ERROR,
		WARNING,
		REFUSED,
		ACCEPT,
		REJECT,
		FAIL,
	}
}
