using System; 
using System.Runtime.Serialization;
using VEIS.Core.Messages;
using VEIS.CpeMediSpanAdapterServiceV3.CRMOL.Messages; 

namespace VEIS.CpeMediSpanAdapterServiceV3.CRMOL.Messages
{ 
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.CpeMediSpanAdapterServiceV3.CRMOL,searchMediSpan method, Request.
	/// Code Generated by IMS on: 5/29/2018 2:55:28 PM
	/// Version: 2018.05.09.05
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISsMSsearchMediSpanRequest : VEISEcRequestBase
    { 
		[DataMember]
		public Guid RelatedParentId { get; set; }
		[DataMember]
		public string RelatedParentEntityName { get; set; }
		[DataMember]
		public string RelatedParentFieldName { get; set; }
		[DataMember]
		public bool LogTiming { get; set; }
		[DataMember]
		public bool LogSoap { get; set; }
		[DataMember]
		public bool Debug { get; set; }
		[DataMember]
		public LegacyHeaderInfo LegacyServiceHeaderInfo { get; set; }
		[DataMember]
		public string mcs_transactionid { get; set; }
		[DataMember]
		public VEISsMSReqCPEMediSpanAdapterv3searchMediSpanRequest VEISsMSReqCPEMediSpanAdapterv3searchMediSpanRequestInfo { get; set; }
	}
	[DataContract]
	public class VEISsMSReqCPEMediSpanAdapterv3searchMediSpanRequest
	{
		[DataMember]
		public DateTime mcs_date { get; set; }
		[DataMember]
		public string mcs_name { get; set; }
		[DataMember]
		public string mcs_ndcNumber { get; set; }
		[DataMember]
		public string mcs_gpiNumber { get; set; }
	}
}
