/**
* @author Jonas Dawson
* @class VIP.store.Epc
*
* Store contains all current values for the EPC codes within Claims.
*/
Ext.define('VIP.store.Epc', {
    extend: 'Ext.data.Store',
    fields: [
        { name: 'label', type: 'string' },
        { name: 'value', type: 'string' },
        { name: 'code', type: 'boolean' }
    ],
    data: [
        { value: '010', label: 'BDD-Initial 8+ issues (010)', code: false },
        { value: '010', label: 'Initial Comp 8+/Pension - Dual Claim (010)', code: false },
        { value: '010', label: 'Initial Compensation 8+ Issues (010)', code: false },
        { value: '010', label: 'PMC-Initial Comp 8+/Pension - Dual Claim (010)', code: false },
        { value: '010', label: 'Predischarge-Initial 8+ issues (010)', code: false },
        { value: '010', label: 'Quick Pay (010)', code: false },
        { value: '020', label: 'BDD-Supplemental (020)', code: false },
        { value: '020', label: 'Claim for Increase (020)', code: false },
        { value: '020', label: 'Helpless child (020)', code: false },
        { value: '020', label: 'PMC-Claim for Increase (020)', code: false },
        { value: '020', label: 'PMC-Helpless child (020)', code: false },
        { value: '020', label: 'PMC-Incompetency Review - S/C (020)', code: false },
        { value: '020', label: 'PMC-Reopened Compensation (020)', code: false },
        { value: '020', label: 'PMC-Special Monthly Compensation (020)', code: false },
        { value: '020', label: 'Predischarge-Supplemental (020)', code: false },
        { value: '020', label: 'Reopened Compensation (020)', code: false },
        { value: '020', label: 'Special Monthly Compensation (020)', code: false },
        { value: '020', label: 'Walk In Claims Pilot (020)', code: false },
        { value: '020', label: 'PMC - Walk In Claims Pilot (020)', code: false },
        { value: '020', label: 'Quick Pay (020)', code: false },
        { value: '025', label: 'Nehmer Readjutication (025)', code: false },
        { value: '025', label: 'Nehmer Adjuctication (025)', code: false },
        { value: '025', label: 'New Herbicide Presumptive (025)', code: false },
        { value: '025', label: 'PMC Nehmer Readjudication (025)', code: false },
        { value: '025', label: 'PMC Nehmer Adjudication (025)', code: false },
        { value: '025', label: 'PMC New Herbicide Presumptive (025)', code: false },
        { value: '050', label: 'EVR (050)', code: false },
        { value: '050', label: 'PMC-EVR (050)', code: false },
        { value: '070', label: 'CERT to BVA (070)', code: false },
        { value: '070', label: 'PMC-Cert to BVA (070)', code: false },
        { value: '070', label: 'PMC-Supplemental Statement of the Case (070)', code: false },
        { value: '070', label: 'Supplemental Statement of the Case (070)', code: false },
        { value: '095', label: 'PMC-Vocational Rehabilitation Eligibility (095)', code: false },
        { value: '095', label: 'Vocational Rehabilitation Eligibility (095)', code: false },
        { value: '110', label: 'BDD-Initial (110)', code: false },
        { value: '110', label: 'Initial Live Comp < 8 issues (110)', code: false },
        { value: '110', label: 'Initial Live Comp/Pension (110)', code: false },
        { value: '110', label: 'PMC-Initial Live Comp/Pension (110)', code: false },
        { value: '110', label: 'Predischarge-Initial (110)', code: false },
        { value: '110', label: 'Walk In Claims Pilot (110)', code: false },
        { value: '110', label: 'PMC - Walk In Claims Pilot (110)', code: false },
        { value: '110', label: 'Quick Pay (110)', code: false },
        { value: '110', label: 'PMC — Quick Pay (110)', code: false },
        { value: '120', label: 'Incompetency Review - Pension (120)', code: false },
        { value: '120', label: 'PMC-Incompetency Review - Pension (120)', code: false },
        { value: '120', label: 'PMC-Reopened Helpless Child (120)', code: false },
        { value: '120', label: 'PMC-Reopened Pension (120)', code: false },
        { value: '120', label: 'PMC-Special Monthly Pension (120)', code: false },
        { value: '120', label: 'Reopened Helpless Child (120)', code: false },
        { value: '120', label: 'Reopened Pension (120)', code: false },
        { value: '120', label: 'Special Monthly Pension (120)', code: false },
        { value: '120', label: 'Walk In Claims Pilot (120)', code: false },
        { value: '120', label: 'PMC - Walk In Claims Pilot (120)', code: false },
        { value: '120', label: 'Quick Pay (120)', code: false },
        { value: '120', label: 'PMC - Quick Pay (120)', code: false },
        { value: '130', label: 'Apportionment (130)', code: false },
        { value: '130', label: 'Dependency (130)', code: false },
        { value: '130', label: 'PMC-Apportionment (130)', code: false },
        { value: '130', label: 'PMC-Dependency (130)', code: false },
        { value: '130', label: 'Walk In Claims Pilot (130)', code: false },
        { value: '130', label: 'PMC - Walk In Claims Pilot (130)', code: false },
        { value: '130', label: 'PMC - Quick Pay (130)', code: false },
        { value: '133', label: 'REPS (133)', code: false },
        { value: '135', label: 'Hospitalization adjustment (135)', code: false },
        { value: '135', label: 'PMC-Hospitalization Adjustment (135)', code: false },
        { value: '140', label: 'PMC - Walk In Claims Pilot (140)', code: false },
        { value: '150', label: 'Election (150)', code: false },
        { value: '150', label: 'Income - Reopened Claim (150)', code: false },
        { value: '150', label: 'Income Adjustment (150)', code: false },
        { value: '150', label: 'Net Worth (150)', code: false },
        { value: '150', label: 'PMC-Election (150)', code: false },
        { value: '150', label: 'PMC-Income - Reopened Claim (150)', code: false },
        { value: '150', label: 'PMC-Income Adjustment (150)', code: false },
        { value: '150', label: 'PMC-Net Worth (150)', code: false },
        { value: '150', label: 'Walk In Claims Pilot (150)', code: false },
        { value: '150', label: 'PMC - Walk In Claims Pilot (150)', code: false },
        { value: '150', label: 'PMC — Quick Pay (150)', code: false },
        { value: '154', label: 'Income Verification Match (154)', code: false },
        { value: '154', label: 'PMC-Income Verification Match (154)', code: false },
        { value: '155', label: 'EVR Referral (155)', code: false },
        { value: '155', label: 'PMC-EVR Referral (155)', code: false },
        { value: '160', label: 'PMC - Walk In Claims Pilot (160)', code: false },
        { value: '165', label: 'PMC - Walk In Claims Pilot (165)', code: false },
        { value: '170', label: 'Appeal Action (170)', code: false },
        { value: '170', label: 'PMC-Appeal Action (170)', code: false },
        { value: '172', label: 'Grant of Benefits (172)', code: false },
        { value: '172', label: 'PMC-Grant of Benefits (172)', code: false },
        { value: '172', label: 'PMC-Statement of the Case (172)', code: false },
        { value: '172', label: 'Statement of the Case (172)', code: false },
        { value: '173', label: 'Formal Hearing by Other Than DRO (173)', code: false },
        { value: '173', label: 'Informal Hearing by DRO (173)', code: false },
        { value: '173', label: 'PMC-Formal Hearing by Other Than DRO (173)', code: false },
        { value: '173', label: 'PMC-Informal Hearing by DRO (173)', code: false },
        { value: '174', label: 'DRO Decision (174)', code: false },
        { value: '174', label: 'Formal Hearing by DRO (174)', code: false },
        { value: '174', label: 'PMC-DRO Decision (174)', code: false },
        { value: '174', label: 'PMC-Formal Hearing by DRO (174)', code: false },
        { value: '180', label: 'Initial Live Pension (180)', code: false },
        { value: '180', label: 'PMC-Initial Live Pension (180)', code: false },
        { value: '180', label: 'Walk In Claims Pilot (180)', code: false },
        { value: '180', label: 'PMC - Walk In Claims Pilot (180)', code: false },
        { value: '180', label: 'Quick Pay (180)', code: false },
        { value: '180', label: 'PMC — Quick Pay (180)', code: false },
        { value: '190', label: 'PMC - Walk In Claims Pilot (190)', code: false },
        { value: '290', label: 'Automobile Allowance (190)', code: false },
        { value: '290', label: 'PMC - Walk In Claims Pilot (290)', code: false },
        { value: '290', label: 'Bureau of SSI Requests (290)', code: false },
        { value: '290', label: 'Clothing Allowance (290)', code: false },
        { value: '290', label: 'Dental Treatment (290)', code: false },
        { value: '290', label: 'Disappearance of Veteran (290)', code: false },
        { value: '290', label: 'Eligibility Determination (290)', code: false },
        { value: '290', label: 'Fiduciary Adjustment (290)', code: false },
        { value: '290', label: 'Hospitalization Eligibility (290)', code: false },
        { value: '290', label: 'Incarceration Adjustment (290)', code: false },
        { value: '290', label: 'Insurance Eligibility (290)', code: false },
        { value: '290', label: 'LGY Eligibility (290)', code: false },
        { value: '290', label: 'Medal of Honor (290)', code: false },
        { value: '290', label: 'Military Pay in Lieu of Comp (290)', code: false },
        { value: '290', label: 'Outpatient Treatment Eligibility (290)', code: false },
        { value: '290', label: 'PMC-Automobile Allowance (290)', code: false },
        { value: '290', label: 'PMC-Bureau of SSI Requests (290)', code: false },
        { value: '290', label: 'PMC-Clothing Allowance (290)', code: false },
        { value: '290', label: 'PMC-Dental Treatment (290)', code: false },
        { value: '290', label: 'PMC-Disappearance of Veteran (290)', code: false },
        { value: '290', label: 'PMC-Eligibility Determination (290)', code: false },
        { value: '290', label: 'PMC-Fiduciary Adjustment (290)', code: false },
        { value: '290', label: 'PMC-Hospitalization Eligibility (290)', code: false },
        { value: '290', label: 'PMC-Incarceration Adjustment (290)', code: false },
        { value: '290', label: 'PMC-Insurance Eligibility (290)', code: false },
        { value: '290', label: 'PMC-LGY Eligibility (290)', code: false },
        { value: '290', label: 'PMC-Medal of Honor (290)', code: false },
        { value: '290', label: 'PMC-Military Pay in Lieu of Comp (290)', code: false },
        { value: '290', label: 'PMC-Outpatient Treatment Eligibility (290)', code: false },
        { value: '290', label: 'PMC-Preference Certificate (290)', code: false },
        { value: '290', label: 'PMC-Renouncement (290)', code: false },
        { value: '290', label: 'PMC-Retired Pay Waiver/Election (290)', code: false },
        { value: '290', label: 'PMC-Return to Active Duty (290)', code: false },
        { value: '290', label: 'PMC-Special Home Adaptation Grant (290)', code: false },
        { value: '290', label: 'PMC-Specially Adapted Housing (290)', code: false },
        { value: '290', label: 'PMC-Vehicular Adaptive Equipment (290)', code: false },
        { value: '290', label: 'Predischarge-LGY Determination (290)', code: false },
        { value: '290', label: 'Predischarge-Resumption of Compensation (290)', code: false },
        { value: '290', label: 'Preference Certificate (290)', code: false },
        { value: '290', label: 'Renouncement (290)', code: false },
        { value: '290', label: 'Retired Pay Waiver/Election (290)', code: false },
        { value: '290', label: 'Return to Active Duty (290)', code: false },
        { value: '290', label: 'Special Home Adaptation Grant (290)', code: false },
        { value: '290', label: 'Specially Adapted Housing (290)', code: false },
        { value: '290', label: 'Vehicular Adaptive Equipment (290)', code: false },
        { value: '290', label: 'Walk In Claims Pilot (290)', code: false },
        { value: '290', label: 'PMC - Walk In Claims Pilot (290)', code: false },
        { value: '290', label: 'Batch CRSC CRDP Payment Made (290)', code: false },
        { value: '293', label: 'COWC (293)', code: false },
        { value: '293', label: 'PMC-COWC (293)', code: false },
        { value: '295', label: 'PMC-Vocational Rehabilitation Determination (295)', code: false },
        { value: '295', label: 'Vocational Rehabilitation Determination (295)', code: false },
        { value: '310', label: 'PMC-Routine Future Exam (310)', code: false },
        { value: '310', label: 'Routine Future Exam (310)', code: false },
        { value: '310', label: 'Quick Pay (310)', code: false },
        { value: '310', label: 'PMC — Quick Pay (310)', code: false },
        { value: '314', label: 'Live Comp IU match IVM (314)', code: false },
        { value: '314', label: 'PMC-Live Comp IU match IVM (314)', code: false },
        { value: '320', label: 'Quick Pay (320)', code: false },
        { value: '320', label: 'PMC — Quick Pay (320)', code: false },
        { value: '320', label: 'PMC-Review Due to Hospitalization (320)', code: false },
        { value: '320', label: 'Review Due to Hospitalization (320)', code: false },
        { value: '320', label: 'Walk In Claims Pilot (320)', code: false },
        { value: '320', label: 'PMC - Walk In Claims Pilot (320)', code: false },
        { value: '330', label: 'PMC-Review (330)', code: false },
        { value: '330', label: 'Review (330)', code: false },
        { value: '400', label: 'Correspondence (400)', code: false },
        { value: '400', label: 'PMC-Correspondence (400)', code: false },
        { value: '500', label: 'PMC-Special Controlled Correspondence (500)', code: false },
        { value: '500', label: 'Special Controlled Correspondence (500)', code: false },
        { value: '510', label: 'FOIA/Privacy Act Request (510)', code: false },
        { value: '510', label: 'PMC-FOIA/Privacy Act Request (150)', code: false },
        { value: '600', label: 'PMC-Predetermination Notice (600)', code: false },
        { value: '600', label: 'Predetermination Notice (600)', code: false },
        { value: '680', label: 'PMC-Reviews - Ratings Involved (680)', code: false },
        { value: '680', label: 'Reviews - Ratings Involved (680)', code: false },
        { value: '682', label: 'PMC-Reviews - Ratings Involved 2 (682)', code: false },
        { value: '682', label: 'Reviews - Ratings Involved 2 (682)', code: false },
        { value: '683', label: 'PMC-Reviews - Ratings Involved 3 (683)', code: false },
        { value: '683', label: 'Reviews - Ratings Involved 3 (683)', code: false },
        { value: '684', label: 'PMC-Reviews - Ratings Involved 4 (684)', code: false },
        { value: '684', label: 'Reviews - Ratings Involved 4 (684)', code: false },
        { value: '687', label: 'Nehmer - IHD - PD - HCL (687)', code: false },
        { value: '689', label: 'Disability Evaluation System (689)', code: false },
        { value: '690', label: 'PMC-Reviews - Authorization Only (690)', code: false },
        { value: '690', label: 'Reviews - Authorization Only (690)', code: false },
        { value: '692', label: 'PMC-Reviews - Authorization Only 2 (692)', code: false },
        { value: '692', label: 'Reviews - Authorization Only 2 (692)', code: false },
        { value: '693', label: 'PMC-Reviews - Authorization Only 3 (693)', code: false },
        { value: '693', label: 'Reviews - Authorization Only 3 (693)', code: false },
        { value: '694', label: 'PMC-Reviews - Authorization Only 4 (694)', code: false },
        { value: '694', label: 'Reviews - Authorization Only 4 (694)', code: false },
        { value: '800', label: '545 Master Record Not Found (800)', code: false },
        { value: '800', label: '548 Returned Payment - No Master Record on File (800)', code: false },
        { value: '800', label: '549 Return of PFOP Withdrawal (800)', code: false },
        { value: '800', label: '549E Unassociated Account Established (800)', code: false },
        { value: '800', label: '562B No Appropriate Deduction - Balance SEG (800)', code: false },
        { value: '800', label: '562C New DED AMT Equals Existing Deduction (800)', code: false },
        { value: '800', label: '562D Deduction Improper--M/R Suspended (800)', code: false },
        { value: '800', label: '562E Cannot Process - Insufficient Source (800)', code: false },
        { value: '800', label: '562F Deduction Not Established - No Address in M/R (800)', code: false },
        { value: '800', label: '565 Detail Name Does Not Match Master (800)', code: false },
        { value: '800', label: '566 Detail Cannot Be Processed Against M/R (800)', code: false },
        { value: '810', label: '100% Unemployable Review (810)', code: false },
        { value: '810', label: '602 Returned PFOP Payment - Master Record Updated (810)', code: false },
        { value: '810', label: '603 Returned Payment Applied to Accts Receivable (810)', code: false },
        { value: '810', label: '604 Unapplied Balance Returned to Appropriation (810)', code: false },
        { value: '810', label: '605 Payee Deceased - Accrual Sgt. Established (810)', code: false },
        { value: '810', label: '606 Payee Deceased - Accrual Segment Increased (810)', code: false },
        { value: '810', label: '607 Miscellaneous Returned Payment (810)', code: false },
        { value: '810', label: '611 Payment Returned Death of Person Entitled (810)', code: false },
        { value: '810', label: '612 Account Suspended-Undeliverable Payment (810)', code: false },
        { value: '810', label: '626 Paid EFT - Verify Home Address (810)', code: false },
        { value: '810', label: '631 Diary Due Date/Reason/Legend (810)', code: false },
        { value: '810', label: '634 Proceeds Established in Participant Record (810)', code: false },
        { value: '810', label: '635 Insurance Deduction SUSP (DISC) EOM (MON) (810)', code: false },
        { value: '810', label: '636 Effect Date DED REQ Changed To (810)', code: false },
        { value: '810', label: '637 Retroactive Change To (810)', code: false },
        { value: '810', label: '643 Change Rejected - Exceeds Current Benefits (810)', code: false },
        { value: '810', label: '647 Deduction Resumed Effective (810)', code: false },
        { value: '810', label: 'Create the following Benefit Claim Label (810)', code: false },
        { value: '810', label: 'Disappearance - 7 Year Review (810)', code: false },
        { value: '810', label: 'EVR Extended Suspense Control (810)', code: false },
        { value: '810', label: 'EVR Selection Control (810)', code: false },
        { value: '810', label: 'EVR Suspense Control (810)', code: false },
        { value: '810', label: 'Expiration of Employability Control (810)', code: false },
        { value: '810', label: 'Follow-Up on Paragraph 28 Review (810)', code: false },
        { value: '810', label: 'Future Physical Examination (810)', code: false },
        { value: '810', label: 'Helpless Child Reaches Majority (810)', code: false },
        { value: '810', label: 'Helpless Child Review (810)', code: false },
        { value: '810', label: 'Issue Dependency Verification Form (810)', code: false },
        { value: '810', label: 'Local Regional Office Special Use (810)', code: false },
        { value: '810', label: 'Paragraph 28 Review (810)', code: false },
        { value: '810', label: 'Philippine Residency Verification (810)', code: false },
        { value: '810', label: 'Reduction Under 38 CFR 3.551(B) (810)', code: false },
        { value: '810', label: 'Reservist Requires Drill Pay Days (810)', code: false },
        { value: '810', label: 'Restore Under 38 CFR 3.556(D) (810)', code: false },
        { value: '810', label: 'Return of Dependency Verification Form (810)', code: false },
        { value: '810', label: 'REV FOR RETURN of VAF 21-4140 (810)', code: false },
        { value: '810', label: 'Review Hardship Expense (810)', code: false },
        { value: '810', label: 'Review Hospital Status Every 6 Months for 2 Years (810)', code: false },
        { value: '810', label: 'Review Need for Reevaluation (810)', code: false },
        { value: '810', label: 'Verify Income or Dependency (810)', code: false },
        { value: '810', label: 'Verify School Attendance (810)', code: false },
        { value: '810', label: 'Veteran Hospitalized 100% Greater Than 3 Months (810)', code: false },
        { value: '810', label: 'VR&E Motivational Contact (810)', code: false },
        { value: '810', label: '633 CH 18 Review Disability Level (810)', code: false },
        { value: '820', label: '777 Clothing Allowance Letter Not Sent', code: false },
        { value: '820', label: '808 Review For Continued Hospital Reduction (820)', code: false },
        { value: '820', label: '811 Notice of VMLI Discontinuance (820)', code: false },
        { value: '820', label: '833A SSA Death DOB Mismatch (820)', code: false },
        { value: '820', label: '833B SSA Death Name Mismatch (820)', code: false },
        { value: '820', label: '833C SSA Death C&P Matched (820)', code: false },
        { value: '820', label: '836 Chng of Addr Notice-VMLI/Spec Housing Involve (820)', code: false },
        { value: '820', label: '842C OPM - Verify Income Rate (820)', code: false },
        { value: '820', label: '842E RRB - Verify Income Rate (820)', code: false },
        { value: '820', label: '842G DOD - Verify Income Rate (820)', code: false },
        { value: '820', label: '850 Paragraph 28 Over xx Months (820)', code: false },
        { value: '820', label: '857 VET Died - VMLI/SPEC/HSG/ Involved (820)', code: false },
        { value: '820', label: '871 VMLI Deduction Established (820)', code: false },
        { value: '820', label: '882 Employability Letter Not Sent (820)', code: false },
        { value: '820', label: '882A EVR Letter Not Written (820)', code: false },
        { value: '820', label: '882B Dependency Verification Letter Not Sent (820)', code: false },
        { value: '820', label: '882C SOC SEC Income Reminder Letter Not Sent (820)', code: false },
        { value: '820', label: '882G Age 18 School Letter Not Sent (820)', code: false },
        { value: '820', label: '882H School Child Verification Letter Not Sent (820)', code: false },
        { value: '820', label: '882I EVR Due Process Letter Not Sent (820)', code: false },
        { value: '820', label: '882J Return Check Due Process Letter Not Sent (820)', code: false },
        { value: '820', label: '882K Manila Verification Letter Not Sent (820)', code: false },
        { value: '820', label: '884 Paragraph 29 Over 3 Months (820)', code: false },
        { value: '820', label: '897 DED AMT Exceeds Total AMT Available (820)', code: false },
        { value: '820', label: '899A SSA - Verify Income Rate (820)', code: false },
        { value: '830', label: '002 File Number (830)', code: false },
        { value: '830', label: '003 Payee Number (830)', code: false },
        { value: '830', label: '005 Person Entitled (830)', code: false },
        { value: '830', label: '006 Trans Code (830)', code: false },
        { value: '830', label: '178 Balance Amount (830)', code: false },
        { value: '830', label: '190 Trans Rejected - Action Code (830)', code: false },
        { value: '830', label: '267 Insurance Effective Date (830)', code: false },
        { value: '830', label: '705 Review Required - RVR Not Returned (830)', code: false },
        { value: '830', label: '999 Multi Records Found on File for Beneficiary (830)', code: false },
        { value: '830', label: 'National Cemetery Administration Notice of Death (830)', code: false },
        { value: '850', label: '850A Legislative Adjustment Required (850)', code: false },
        { value: '930', label: 'PMC-Rvw/Ref/Other (930)', code: false },
        { value: '930', label: 'Rvw/Ref/Other (930)', code: false },
        { value: '960', label: 'Administrative Error (960)', code: false },
        { value: '960', label: 'PMC-Administrative Error (960)', code: false },
        { label: '010', value: '010', code: true },
        { label: '020', value: '020', code: true },
        { label: '025', value: '025', code: true },
        { label: '050', value: '050', code: true },
        { label: '070', value: '070', code: true },
        { label: '095', value: '095', code: true },
        { label: '110', value: '110', code: true },
        { label: '120', value: '120', code: true },
        { label: '130', value: '130', code: true },
        { label: '133', value: '133', code: true },
        { label: '135', value: '135', code: true },
        { label: '140', value: '140', code: true },
        { label: '150', value: '150', code: true },
        { label: '154', value: '154', code: true },
        { label: '155', value: '155', code: true },
        { label: '160', value: '160', code: true },
        { label: '165', value: '165', code: true },
        { label: '170', value: '170', code: true },
        { label: '172', value: '172', code: true },
        { label: '173', value: '173', code: true },
        { label: '174', value: '174', code: true },
        { label: '180', value: '180', code: true },
        { label: '190', value: '190', code: true },
        { label: '290', value: '290', code: true },
        { label: '293', value: '293', code: true },
        { label: '295', value: '295', code: true },
        { label: '310', value: '310', code: true },
        { label: '314', value: '314', code: true },
        { label: '320', value: '320', code: true },
        { label: '330', value: '330', code: true },
        { label: '400', value: '400', code: true },
        { label: '500', value: '500', code: true },
        { label: '510', value: '510', code: true },
        { label: '600', value: '600', code: true },
        { label: '680', value: '680', code: true },
        { label: '682', value: '682', code: true },
        { label: '683', value: '683', code: true },
        { label: '684', value: '684', code: true },
        { label: '687', value: '687', code: true },
        { label: '689', value: '689', code: true },
        { label: '690', value: '690', code: true },
        { label: '692', value: '692', code: true },
        { label: '693', value: '693', code: true },
        { label: '694', value: '694', code: true },
        { label: '800', value: '800', code: true },
        { label: '810', value: '810', code: true },
        { label: '820', value: '820', code: true },
        { label: '830', value: '830', code: true },
        { label: '850', value: '850', code: true },
        { label: '930', value: '930', code: true },
        { label: '960', value: '960', code: true }
    ]
});