using System;
using System.Runtime.Serialization;
using UDO.LOB.Core;

//using Microsoft.Xrm.Sdk;
//using VRM.Integration.Servicebus.Core;
//using VRM.Integration.UDO.Messages;

/// <summary>
/// VIMT LOB Component for UDOcreateUDOLifecycles,createUDOLifecycles method, Response.
/// Code Generated by IMS on: 5/29/2015 3:11:20 PM
/// Version: 2015.05.05
/// </summary>
/// <param name=none></param>
/// <returns>none</returns>

namespace UDO.LOB.Claims.Messages
{
    //[Export(typeof(IMessageBase))]
    //[ExportMetadata("MessageType", MessageRegistry.UDOcreateUDOLifecyclesResponse)]
    [DataContract]
    public class UDOcreateUDOLifecyclesResponse : MessageBase
    {
        [DataMember]
        public bool ExceptionOccured { get; set; }
        [DataMember]
        public string ExceptionMessage { get; set; }
        [DataMember]
        public UDOcreateUDOLifecyclesMultipleResponse[] UDOcreateUDOLifecyclesInfo { get; set; }
    }
    [DataContract]
    public class UDOcreateUDOLifecyclesMultipleResponse
    {
        [DataMember]
        public Guid newUDOcreateUDOLifecyclesId { get; set; }
    }
}