using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.PaymentInformationService.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.PaymentInformationService,retrievePaymentDetail method, Request.
	/// Code Generated by IMS on: 12/27/2018 4:55:08 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISrtrpmtdtlretrievePaymentDetailRequest : VEISEcRequestBase
	{
		[DataMember]
		public Guid RelatedParentId { get; set; }
		[DataMember]
		public string RelatedParentEntityName { get; set; }
		[DataMember]
		public string RelatedParentFieldName { get; set; }
		[DataMember]
		public bool LogTiming { get; set; }
		[DataMember]
		public bool LogSoap { get; set; }
		[DataMember]
		public bool Debug { get; set; }
		[DataMember]
		public LegacyHeaderInfo LegacyServiceHeaderInfo { get; set; }
		[DataMember]
		public Int64 mcs_paymentid { get; set; }
		[DataMember]
		public Int64 mcs_fbtid { get; set; }
	}
}
