using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.PaymentInformationService.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.PaymentInformationService,retrievePaymentSummaryWithBDN method, Request.
	/// Code Generated by IMS on: 12/27/2018 5:00:18 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISrtvpmtsumbdnrretrievePaymentSummaryWithBDNRequest : VEISEcRequestBase
	{
		[DataMember]
		public Guid RelatedParentId { get; set; }
		[DataMember]
		public string RelatedParentEntityName { get; set; }
		[DataMember]
		public string RelatedParentFieldName { get; set; }
		[DataMember]
		public bool LogTiming { get; set; }
		[DataMember]
		public bool LogSoap { get; set; }
		[DataMember]
		public bool Debug { get; set; }
		[DataMember]
		public LegacyHeaderInfo LegacyServiceHeaderInfo { get; set; }
		[DataMember]
		public Int64 mcs_participantid { get; set; }
		[DataMember]
		public string mcs_filenumber { get; set; }
		[DataMember]
		public string mcs_payeecode { get; set; }
	}
}
