using System;
using System.ComponentModel.Composition;
using Microsoft.Xrm.Sdk;
using System.Runtime.Serialization;
using VRM.Integration.Servicebus.Core;
using VRM.Integration.UDO.Common.Messages;
using VRM.Integration.UDO.Messages;

/// <summary>
/// VIMT LOB Component for UDOInitiateSR,InitiateSR method, Request.
/// Code Generated by IMS on: 8/4/2015 10:18:38 AM
/// Version: 2015.06.02
/// </summary>
/// <param name=none></param>
/// <returns>none</returns>
namespace VRM.Integration.UDO.ServiceRequest.Messages
{
    [Export(typeof(IMessageBase))]
    [ExportMetadata("MessageType", MessageRegistry.UDOInitiateSRRequest)]
    [DataContract]
    public class UDOInitiateSRRequest : UDORequestBase
    {
        [DataMember]
        public string udo_InteractionId { get; set; }
        [DataMember]
        public string udo_PersonId { get; set; }
        [DataMember]
        public string udo_IDProofId { get; set; }
        [DataMember]
        public string udo_VeteranId { get; set; }
        [DataMember]
        public string udo_RequestType { get; set; }
        [DataMember]
        public string udo_RequestSubType { get; set; }
        [DataMember]
        public UDOInitiateSRRelatedEntitiesMultipleRequest[] UDOInitiateSRRelatedEntitiesInfo { get; set; }
    }
    [DataContract]
    public class UDOInitiateSRRelatedEntitiesMultipleRequest
    {
        [DataMember]
        public string RelatedEntityName { get; set; }
        [DataMember]
        public Guid RelatedEntityId { get; set; }
        [DataMember]
        public string RelatedEntityFieldName { get; set; }
    }
}