using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.ClaimantService.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.ClaimantService,findDepositAccount method, Response.
	/// Code Generated by IMS on: 12/19/2018 9:29:37 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISfdepaccfindDepositAccountResponse : VEISEcResponseBase
	{
		[DataMember]
		public VEISfdepaccreturn VEISfdepaccreturnInfo { get; set; }
	}
	[DataContract]
	public class VEISfdepaccreturn
	{
		[DataMember]
		public string mcs_accountNbr { get; set; }
		[DataMember]
		public string mcs_accountTypeName { get; set; }
		[DataMember]
		public string mcs_beginDate { get; set; }
		[DataMember]
		public string mcs_endDate { get; set; }
		[DataMember]
		public string mcs_jrnDt { get; set; }
		[DataMember]
		public string mcs_jrnLctnId { get; set; }
		[DataMember]
		public string mcs_jrnObjId { get; set; }
		[DataMember]
		public string mcs_jrnStatusTypeCd { get; set; }
		[DataMember]
		public string mcs_jrnUserId { get; set; }
		[DataMember]
		public string mcs_ptcpntDepositAccountId { get; set; }
		[DataMember]
		public string mcs_routingTransitNbr { get; set; }
		[DataMember]
		public string mcs_treasurySeqNbr { get; set; }
		[DataMember]
		public string mcs_typeName { get; set; }
	}
}
