using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.ClaimantService.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.ClaimantService,findPaymentAddress method, Response.
	/// Code Generated by IMS on: 12/19/2018 9:52:31 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISfpayaddfindPaymentAddressResponse : VEISEcResponseBase
	{
		[DataMember]
		public VEISfpayaddreturn VEISfpayaddreturnInfo { get; set; }
	}
	[DataContract]
	public class VEISfpayaddreturn
	{
		[DataMember]
		public string mcs_addressLine1 { get; set; }
		[DataMember]
		public string mcs_addressLine2 { get; set; }
		[DataMember]
		public string mcs_addressLine3 { get; set; }
		[DataMember]
		public string mcs_badAddressIndicator { get; set; }
		[DataMember]
		public string mcs_city { get; set; }
		[DataMember]
		public string mcs_countryTypeName { get; set; }
		[DataMember]
		public string mcs_county { get; set; }
		[DataMember]
		public string mcs_effectiveDate { get; set; }
		[DataMember]
		public string mcs_eftWaiverTypeName { get; set; }
		[DataMember]
		public string mcs_email { get; set; }
		[DataMember]
		public string mcs_endDate { get; set; }
		[DataMember]
		public string mcs_forignPostalCode { get; set; }
		[DataMember]
		public string mcs_jrnDt { get; set; }
		[DataMember]
		public string mcs_jrnLctnId { get; set; }
		[DataMember]
		public string mcs_jrnObjId { get; set; }
		[DataMember]
		public string mcs_jrnStatusTypeCd { get; set; }
		[DataMember]
		public string mcs_jrnUserId { get; set; }
		[DataMember]
		public string mcs_militaryPostOfficeTypeCode { get; set; }
		[DataMember]
		public string mcs_militaryPostalTypeCode { get; set; }
		[DataMember]
		public string mcs_province { get; set; }
		[DataMember]
		public string mcs_ptcpntAddressId { get; set; }
		[DataMember]
		public string mcs_state { get; set; }
		[DataMember]
		public string mcs_territory { get; set; }
		[DataMember]
		public string mcs_treasuryAddress1 { get; set; }
		[DataMember]
		public string mcs_treasuryAddress2 { get; set; }
		[DataMember]
		public string mcs_treasuryAddress3 { get; set; }
		[DataMember]
		public string mcs_treasuryAddress4 { get; set; }
		[DataMember]
		public string mcs_treasuryAddress5 { get; set; }
		[DataMember]
		public string mcs_treasuryAddress6 { get; set; }
		[DataMember]
		public string mcs_treasurySequenceNumber { get; set; }
		[DataMember]
		public string mcs_typeName { get; set; }
		[DataMember]
		public string mcs_verifiedInd { get; set; }
		[DataMember]
		public string mcs_zipFirstSuffix { get; set; }
		[DataMember]
		public string mcs_zipPrefix { get; set; }
		[DataMember]
		public string mcs_zipSecondSuffix { get; set; }
	}
}
