using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.ClaimantService.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.ClaimantService,findMilitaryRecordByPtcpntId method, Response.
	/// Code Generated by IMS on: 12/19/2018 9:47:50 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISfmirecpicfindMilitaryRecordByPtcpntIdResponse : VEISEcResponseBase
	{
		[DataMember]
		public VEISfmirecpicreturn VEISfmirecpicreturnInfo { get; set; }
	}
	[DataContract]
	public class VEISfmirecpicreturn
	{
		[DataMember]
		public string mcs_numberOfMilitaryPersonDecorationRecords { get; set; }
		[DataMember]
		public string mcs_numberOfMilitaryPersonPowRecords { get; set; }
		[DataMember]
		public string mcs_numberOfMilitaryPersonRecords { get; set; }
		[DataMember]
		public string mcs_numberOfMilitaryPersonTourRecords { get; set; }
		[DataMember]
		public string mcs_numberOfMilitaryReadjustmentBalanceRecords { get; set; }
		[DataMember]
		public string mcs_numberOfMilitaryReadjustmentPayRecords { get; set; }
		[DataMember]
		public string mcs_numberOfMilitaryRetirementPayRecords { get; set; }
		[DataMember]
		public string mcs_numberOfMilitarySeperationBalanceRecords { get; set; }
		[DataMember]
		public string mcs_numberOfMilitarySeperationPayRecords { get; set; }
		[DataMember]
		public string mcs_numberOfMilitarySeveranceBalanceRecords { get; set; }
		[DataMember]
		public string mcs_numberOfMilitarySeverancePayRecords { get; set; }
		[DataMember]
		public string mcs_numberOfMilitaryTheatreRecords { get; set; }
		[DataMember]
		public VEISfmirecpicmilitaryPersonDecorationsMultipleResponse[] VEISfmirecpicmilitaryPersonDecorationsInfo { get; set; }
		[DataMember]
		public VEISfmirecpicmilitaryPersonPowsMultipleResponse[] VEISfmirecpicmilitaryPersonPowsInfo { get; set; }
		[DataMember]
		public VEISfmirecpicmilitaryPersonToursMultipleResponse[] VEISfmirecpicmilitaryPersonToursInfo { get; set; }
		[DataMember]
		public VEISfmirecpicmilitaryPersonsMultipleResponse[] VEISfmirecpicmilitaryPersonsInfo { get; set; }
		[DataMember]
		public VEISfmirecpicmilitaryReadjustmentBalancesMultipleResponse[] VEISfmirecpicmilitaryReadjustmentBalancesInfo { get; set; }
		[DataMember]
		public VEISfmirecpicmilitaryReadjustmentPaysMultipleResponse[] VEISfmirecpicmilitaryReadjustmentPaysInfo { get; set; }
		[DataMember]
		public VEISfmirecpicmilitaryRetirementPaysMultipleResponse[] VEISfmirecpicmilitaryRetirementPaysInfo { get; set; }
		[DataMember]
		public VEISfmirecpicmilitarySeperationBalancesMultipleResponse[] VEISfmirecpicmilitarySeperationBalancesInfo { get; set; }
		[DataMember]
		public VEISfmirecpicmilitarySeperationPaysMultipleResponse[] VEISfmirecpicmilitarySeperationPaysInfo { get; set; }
		[DataMember]
		public VEISfmirecpicmilitarySeveranceBalancesMultipleResponse[] VEISfmirecpicmilitarySeveranceBalancesInfo { get; set; }
		[DataMember]
		public VEISfmirecpicmilitarySeverancePaysMultipleResponse[] VEISfmirecpicmilitarySeverancePaysInfo { get; set; }
		[DataMember]
		public VEISfmirecpicmilitaryTheatresMultipleResponse[] VEISfmirecpicmilitaryTheatresInfo { get; set; }
	}
	[DataContract]
	public class VEISfmirecpicmilitaryPersonDecorationsMultipleResponse
	{
		[DataMember]
		public string mcs_militaryDecorationId { get; set; }
		[DataMember]
		public string mcs_militaryDecorationName { get; set; }
		[DataMember]
		public string mcs_ptcpntId { get; set; }
	}
	[DataContract]
	public class VEISfmirecpicmilitaryPersonPowsMultipleResponse
	{
		[DataMember]
		public string mcs_campSectorTxt { get; set; }
		[DataMember]
		public string mcs_captorTxt { get; set; }
		[DataMember]
		public string mcs_captureDate { get; set; }
		[DataMember]
		public string mcs_days { get; set; }
		[DataMember]
		public string mcs_militaryPersonPowSeqNbr { get; set; }
		[DataMember]
		public string mcs_militaryTheatreTypeName { get; set; }
		[DataMember]
		public string mcs_powCountryTypeCd { get; set; }
		[DataMember]
		public string mcs_ptcpntId { get; set; }
		[DataMember]
		public string mcs_releaseDate { get; set; }
		[DataMember]
		public string mcs_underThirtyDaysInd { get; set; }
		[DataMember]
		public string mcs_verifiedInd { get; set; }
	}
	[DataContract]
	public class VEISfmirecpicmilitaryPersonToursMultipleResponse
	{
		[DataMember]
		public string mcs_daysActiveQty { get; set; }
		[DataMember]
		public string mcs_dischargePayGradeName { get; set; }
		[DataMember]
		public string mcs_eodDate { get; set; }
		[DataMember]
		public string mcs_lostTimeDaysNbr { get; set; }
		[DataMember]
		public string mcs_militaryBranchInd { get; set; }
		[DataMember]
		public string mcs_militaryDutyVaPurposeTypeCd { get; set; }
		[DataMember]
		public string mcs_militaryPersonTourNbr { get; set; }
		[DataMember]
		public string mcs_militarySeperationNarritiveTypeCd { get; set; }
		[DataMember]
		public string mcs_militarySeperationReasonTypeName { get; set; }
		[DataMember]
		public string mcs_militarySvcBranchTypeName { get; set; }
		[DataMember]
		public string mcs_militarySvcOtherBranchTypeName { get; set; }
		[DataMember]
		public string mcs_militaryTourSvcStatusTypeName { get; set; }
		[DataMember]
		public string mcs_mpDischargeAuthorityTypeName { get; set; }
		[DataMember]
		public string mcs_mpDischargeCharTypeName { get; set; }
		[DataMember]
		public string mcs_payGradeTypeName { get; set; }
		[DataMember]
		public string mcs_ptcpntId { get; set; }
		[DataMember]
		public string mcs_radDate { get; set; }
		[DataMember]
		public string mcs_serviceNbr { get; set; }
		[DataMember]
		public string mcs_sixYearObligationDate { get; set; }
		[DataMember]
		public string mcs_travelTimeDaysNbr { get; set; }
		[DataMember]
		public string mcs_travelTimeVerifiedInd { get; set; }
		[DataMember]
		public string mcs_vadsCd { get; set; }
		[DataMember]
		public string mcs_varInd { get; set; }
		[DataMember]
		public string mcs_verifiedInd { get; set; }
		[DataMember]
		public string mcs_warTimeSvcCountryName { get; set; }
		[DataMember]
		public string mcs_warTimeSvcInd { get; set; }
	}
	[DataContract]
	public class VEISfmirecpicmilitaryPersonsMultipleResponse
	{
		[DataMember]
		public string mcs_activeDutyStatusInd { get; set; }
		[DataMember]
		public string mcs_deathInSvcInd { get; set; }
		[DataMember]
		public string mcs_disabilitySvcInd { get; set; }
		[DataMember]
		public string mcs_gulfWarRegistryInd { get; set; }
		[DataMember]
		public string mcs_incompetentInd { get; set; }
		[DataMember]
		public string mcs_insuranceFileNumber { get; set; }
		[DataMember]
		public string mcs_insurancePolicyNumber { get; set; }
		[DataMember]
		public string mcs_lgyEntitlementAmount { get; set; }
		[DataMember]
		public string mcs_ptcpntId { get; set; }
		[DataMember]
		public string mcs_reserveInd { get; set; }
		[DataMember]
		public string mcs_totalActiveSvcDays { get; set; }
		[DataMember]
		public string mcs_totalActiveSvcMonths { get; set; }
		[DataMember]
		public string mcs_totalActiveSvcYears { get; set; }
	}
	[DataContract]
	public class VEISfmirecpicmilitaryReadjustmentBalancesMultipleResponse
	{
		[DataMember]
		public string mcs_currentBalance { get; set; }
		[DataMember]
		public string mcs_dateOfZeroBalance { get; set; }
		[DataMember]
		public string mcs_originalBalance { get; set; }
	}
	[DataContract]
	public class VEISfmirecpicmilitaryReadjustmentPaysMultipleResponse
	{
		[DataMember]
		public string mcs_grossAmount { get; set; }
		[DataMember]
		public string mcs_lessFedTaxAmount { get; set; }
		[DataMember]
		public string mcs_lineItemNbr { get; set; }
		[DataMember]
		public string mcs_ptcpntId { get; set; }
		[DataMember]
		public string mcs_reasonTxt { get; set; }
		[DataMember]
		public string mcs_receiptDate { get; set; }
		[DataMember]
		public string mcs_usCodeReasonTxt { get; set; }
	}
	[DataContract]
	public class VEISfmirecpicmilitaryRetirementPaysMultipleResponse
	{
		[DataMember]
		public string mcs_effectiveDate { get; set; }
		[DataMember]
		public string mcs_fullWaiverInd { get; set; }
		[DataMember]
		public string mcs_grossMonthlyAmount { get; set; }
		[DataMember]
		public string mcs_lessFedTaxAmount { get; set; }
		[DataMember]
		public string mcs_lineItemNbr { get; set; }
		[DataMember]
		public string mcs_ptcpntId { get; set; }
		[DataMember]
		public string mcs_retirementPayTypeCd { get; set; }
		[DataMember]
		public string mcs_retirementWaivedDate { get; set; }
		[DataMember]
		public string mcs_sbpOverpaymentAmount { get; set; }
	}
	[DataContract]
	public class VEISfmirecpicmilitarySeperationBalancesMultipleResponse
	{
		[DataMember]
		public string mcs_currentBalance { get; set; }
		[DataMember]
		public string mcs_dateOfZeroBalance { get; set; }
		[DataMember]
		public string mcs_originalBalance { get; set; }
	}
	[DataContract]
	public class VEISfmirecpicmilitarySeperationPaysMultipleResponse
	{
		[DataMember]
		public string mcs_grossAmount { get; set; }
		[DataMember]
		public string mcs_lessFedTaxAmount { get; set; }
		[DataMember]
		public string mcs_lineItemNbr { get; set; }
		[DataMember]
		public string mcs_ptcpntId { get; set; }
		[DataMember]
		public string mcs_receiptDate { get; set; }
	}
	[DataContract]
	public class VEISfmirecpicmilitarySeveranceBalancesMultipleResponse
	{
		[DataMember]
		public string mcs_currentBalance { get; set; }
		[DataMember]
		public string mcs_dateOfZeroBalance { get; set; }
		[DataMember]
		public string mcs_originalBalance { get; set; }
	}
	[DataContract]
	public class VEISfmirecpicmilitarySeverancePaysMultipleResponse
	{
		[DataMember]
		public string mcs_disabilityTxt { get; set; }
		[DataMember]
		public string mcs_grossAmount { get; set; }
		[DataMember]
		public string mcs_lessFedTaxAmount { get; set; }
		[DataMember]
		public string mcs_lineItemNbr { get; set; }
		[DataMember]
		public string mcs_ptcpntId { get; set; }
	}
	[DataContract]
	public class VEISfmirecpicmilitaryTheatresMultipleResponse
	{
		[DataMember]
		public string mcs_beginDate { get; set; }
		[DataMember]
		public string mcs_days { get; set; }
		[DataMember]
		public string mcs_endDate { get; set; }
		[DataMember]
		public string mcs_militaryPersonTourNbr { get; set; }
		[DataMember]
		public string mcs_militaryTheatreTypeName { get; set; }
		[DataMember]
		public string mcs_ptcpntId { get; set; }
		[DataMember]
		public string mcs_verifiedInd { get; set; }
	}
}
