using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.ClaimantService.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.ClaimantService,findDependents method, Response.
	/// Code Generated by IMS on: 12/19/2018 9:28:09 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISfedpfindDependentsResponse : VEISEcResponseBase
	{
		[DataMember]
		public VEISfedpreturn VEISfedpreturnInfo { get; set; }
	}
	[DataContract]
	public class VEISfedpreturn
	{
		[DataMember]
		public string mcs_numberOfRecords { get; set; }
		[DataMember]
		public string mcs_returnCode { get; set; }
		[DataMember]
		public string mcs_returnMessage { get; set; }
		[DataMember]
		public VEISfedppersonsMultipleResponse[] VEISfedppersonsInfo { get; set; }
	}
	[DataContract]
	public class VEISfedppersonsMultipleResponse
	{
		[DataMember]
		public string mcs_awardIndicator { get; set; }
		[DataMember]
		public string mcs_cityOfBirth { get; set; }
		[DataMember]
		public string mcs_currentRelateStatus { get; set; }
		[DataMember]
		public string mcs_dateOfBirth { get; set; }
		[DataMember]
		public string mcs_dateOfDeath { get; set; }
		[DataMember]
		public string mcs_deathReason { get; set; }
		[DataMember]
		public string mcs_emailAddress { get; set; }
		[DataMember]
		public string mcs_firstName { get; set; }
		[DataMember]
		public string mcs_gender { get; set; }
		[DataMember]
		public string mcs_lastName { get; set; }
		[DataMember]
		public string mcs_middleName { get; set; }
		[DataMember]
		public string mcs_proofOfDependency { get; set; }
		[DataMember]
		public string mcs_ptcpntId { get; set; }
		[DataMember]
		public string mcs_relateToVeteran { get; set; }
		[DataMember]
		public string mcs_relatedToVet { get; set; }
		[DataMember]
		public string mcs_relationship { get; set; }
		[DataMember]
		public string mcs_spaces { get; set; }
		[DataMember]
		public string mcs_ssn { get; set; }
		[DataMember]
		public string mcs_ssnVerifyStatus { get; set; }
		[DataMember]
		public string mcs_stateOfBirth { get; set; }
		[DataMember]
		public string mcs_veteranIndicator { get; set; }
	}
}
