using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.ClaimantService.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.ClaimantService,findGeneralInformationByPtcpntId method, Request.
	/// Code Generated by IMS on: 12/19/2018 9:36:03 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISfgenpidfindGeneralInformationByPtcpntIdRequest : VEISEcRequestBase
	{
		[DataMember]
		public Guid RelatedParentId { get; set; }
		[DataMember]
		public string RelatedParentEntityName { get; set; }
		[DataMember]
		public string RelatedParentFieldName { get; set; }
		[DataMember]
		public bool LogTiming { get; set; }
		[DataMember]
		public bool LogSoap { get; set; }
		[DataMember]
		public bool Debug { get; set; }
		[DataMember]
		public LegacyHeaderInfo LegacyServiceHeaderInfo { get; set; }
		[DataMember]
		public Int64 mcs_ptcpntid { get; set; }
        // TODO: Added manually as these next three below were not in VEIS Messages as of 3/12/19
        [DataMember]
        public string mcs_ptcpntvetid { get; set; }
        [DataMember]
        public string mcs_ptcpntbeneid { get; set; }
        [DataMember]
        public string mcs_ptpcntrecipid { get; set; }
        [DataMember]
        public string mcs_filenumber { get; set; }
        // UDO Mig team added this as it was missing 
        [DataMember]
        public string mcs_awardtypecd { get; set; }
    }
}
