using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.VVADocOperations.Api.Messages
{ 
    [DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.VVADocOperations,AddDocument method, Request.
	/// Code Generated by IMS on: 2/10/2016 12:12:38 PM
	/// Version: 2016.2.4.1
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISvvado_AddDocumentRequest : VEISEcRequestBase
    { 
		[DataMember]
		public Guid RelatedParentId { get; set; }
		[DataMember]
		public string RelatedParentEntityName { get; set; }
		[DataMember]
		public string RelatedParentFieldName { get; set; }
		[DataMember]
		public bool LogTiming { get; set; }
		[DataMember]
		public bool LogSoap { get; set; }
		[DataMember]
		public bool Debug { get; set; }
		[DataMember]
		public LegacyHeaderInfo LegacyServiceHeaderInfo { get; set; }
		[DataMember]
		public VEISvvado_vadocument vadocumentInfo { get; set; }
	}
	public class VEISvvado_vadocument
	{
		[DataMember]
		public Byte[] mcs_content { get; set; }
		[DataMember]
		public string mcs_documentTitle { get; set; }
		[DataMember]
		public string mcs_fileName { get; set; }
		[DataMember]
		public string mcs_claimNumber { get; set; }
		[DataMember]
		public DateTime mcs_dateOfReceipt { get; set; }
		[DataMember]
		public bool mcs_dateOfReceiptSpecified { get; set; }
		[DataMember]
		public Int32 mcs_documentType { get; set; }
		[DataMember]
		public string mcs_documentSubject { get; set; }
		[DataMember]
		public string mcs_insertedByUserId { get; set; }
		[DataMember]
		public string mcs_insertedByRO { get; set; }
		[DataMember]
		public string mcs_sourceComment { get; set; }
		[DataMember]
		public string mcs_source { get; set; }
		[DataMember]
		public Int32 mcs_documentCategory { get; set; }
		[DataMember]
		public string mcs_mimeType { get; set; }
	}
}
