using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.VVADocOperations.Api.Messages
{
    [DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.VVADocOperations,AddDocument method, Response.
	/// Code Generated by IMS on: 2/10/2016 12:12:38 PM
	/// Version: 2016.2.4.1
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISvvado_AddDocumentResponse : VEISEcResponseBase
    {
		[DataMember]
        public VEISvvado_Nullable1 VEISvvado_Nullable1Info { get; set; }
		[DataMember]
		public bool ExceptionOccured { get; set; } 
	}
	[DataContract]
	public class VEISvvado_Nullable1
	{
	}
}
