using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.ClaimAdapterService.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.ClaimAdapterService,findClaimsByPDI method, Response.
	/// Code Generated by IMS on: 1/11/2019 8:42:54 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISfclmbpdifindClaimsByPDIResponse : VEISEcResponseBase
	{
		[DataMember]
		public VEISfclmbpdiCPEClaimAdapterv2findClaimsByPDIResponse1 VEISfclmbpdiCPEClaimAdapterv2findClaimsByPDIResponse1Info { get; set; }
	}
	[DataContract]
	public class VEISfclmbpdiCPEClaimAdapterv2findClaimsByPDIResponse1
	{
		[DataMember]
		public VEISfclmbpdiclaimsMultipleResponse[] VEISfclmbpdiclaimsInfo { get; set; }
		[DataMember]
		public VEISfclmbpdiresponseStats VEISfclmbpdiresponseStatsInfo { get; set; }
		[DataMember]
		public VEISfclmbpdifault VEISfclmbpdifaultInfo { get; set; }
	}
	[DataContract]
	public class VEISfclmbpdiclaimsMultipleResponse
	{
		[DataMember]
		public string mcs_claimNumber { get; set; }
		[DataMember]
		public String[] mcs_pdiNumbers { get; set; }
		[DataMember]
		public DateTime mcs_dateOfService { get; set; }
		[DataMember]
		public bool mcs_dateOfServiceSpecified { get; set; }
		[DataMember]
		public string mcs_providerName { get; set; }
		[DataMember]
		public string mcs_billCharged { get; set; }
		[DataMember]
		public string mcs_allowedAmount { get; set; }
		[DataMember]
		public string mcs_primaryOHI { get; set; }
		[DataMember]
		public string mcs_secondaryOHI { get; set; }
		[DataMember]
		public string mcs_champVAPayment { get; set; }
		[DataMember]
		public string mcs_deductibleAmount { get; set; }
		[DataMember]
		public string mcs_costShare { get; set; }
		[DataMember]
		public string mcs_assignBenefitsFlag { get; set; }
		[DataMember]
		public VEISfclmbpdiclaimStatus VEISfclmbpdiclaimStatusInfo { get; set; }
		[DataMember]
		public VEISfclmbpdiplaceOfService VEISfclmbpdiplaceOfServiceInfo { get; set; }
		[DataMember]
		public VEISfclmbpdirejectReasonsMultipleResponse[] VEISfclmbpdirejectReasonsInfo { get; set; }
		[DataMember]
		public VEISfclmbpdiclaimCommentMultipleResponse[] VEISfclmbpdiclaimCommentInfo { get; set; }
	}
	[DataContract]
	public class VEISfclmbpdiclaimStatus
	{
		[DataMember]
		public string mcs_code { get; set; }
		[DataMember]
		public string mcs_description { get; set; }
	}
	[DataContract]
	public class VEISfclmbpdiplaceOfService
	{
		[DataMember]
		public string mcs_code { get; set; }
		[DataMember]
		public string mcs_description { get; set; }
	}
	[DataContract]
	public class VEISfclmbpdirejectReasonsMultipleResponse
	{
		[DataMember]
		public VEISfclmbpdirejectReason VEISfclmbpdirejectReasonInfo { get; set; }
	}
	[DataContract]
	public class VEISfclmbpdirejectReason
	{
		[DataMember]
		public string mcs_code { get; set; }
		[DataMember]
		public string mcs_description { get; set; }
	}
	[DataContract]
	public class VEISfclmbpdiclaimCommentMultipleResponse
	{
		[DataMember]
		public DateTime mcs_dateEntered { get; set; }
		[DataMember]
		public bool mcs_dateEnteredSpecified { get; set; }
		[DataMember]
		public string mcs_source { get; set; }
		[DataMember]
		public string mcs_comment { get; set; }
		[DataMember]
		public VEISfclmbpdienteredBy VEISfclmbpdienteredByInfo { get; set; }
	}
	[DataContract]
	public class VEISfclmbpdienteredBy
	{
		[DataMember]
		public string mcs_prefix { get; set; }
		[DataMember]
		public string mcs_firstName { get; set; }
		[DataMember]
		public string mcs_middleName { get; set; }
		[DataMember]
		public string mcs_lastName { get; set; }
		[DataMember]
		public string mcs_suffix { get; set; }
	}
	[DataContract]
	public class VEISfclmbpdiresponseStats
	{
		[DataMember]
		public Int32 mcs_recordsReturned { get; set; }
		[DataMember]
		public bool mcs_recordsReturnedSpecified { get; set; }
		[DataMember]
		public bool mcs_moreChunkRecords { get; set; }
		[DataMember]
		public bool mcs_moreChunkRecordsSpecified { get; set; }
		[DataMember]
		public bool mcs_moreDateRecords { get; set; }
		[DataMember]
		public bool mcs_moreDateRecordsSpecified { get; set; }
		[DataMember]
		public Int32 mcs_totalRecords { get; set; }
		[DataMember]
		public bool mcs_totalRecordsSpecified { get; set; }
	}
	[DataContract]
	public class VEISfclmbpdifault
	{
		[DataMember]
		public bool mcs_essCodeSpecified { get; set; }
		[DataMember]
		public string mcs_essText { get; set; }
		[DataMember]
		public string mcs_code { get; set; }
		[DataMember]
		public string mcs_text { get; set; }
		[DataMember]
		public VEISfclmbpdiessCode VEISfclmbpdiessCodeInfo { get; set; }
		[DataMember]
		public VEISfclmbpdinestedFault VEISfclmbpdinestedFaultInfo { get; set; }
	}
	[DataContract]
	public enum VEISfclmbpdiessCode
	{
		SUCCESS,
		ERROR,
		WARNING,
		REFUSED,
		ACCEPT,
		REJECT,
		FAIL,
	}
	[DataContract]
	public class VEISfclmbpdinestedFault
	{
		[DataMember]
		public bool mcs_essCodeSpecified { get; set; }
		[DataMember]
		public string mcs_essText { get; set; }
		[DataMember]
		public string mcs_code { get; set; }
		[DataMember]
		public string mcs_text { get; set; }
		[DataMember]
		public VEISfclmbpdiessCode1 VEISfclmbpdiessCode1Info { get; set; }
	}
	[DataContract]
	public enum VEISfclmbpdiessCode1
	{
		SUCCESS,
		ERROR,
		WARNING,
		REFUSED,
		ACCEPT,
		REJECT,
		FAIL,
	}
}
