using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.ClaimAdapterService.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.ClaimAdapterService,findClaimsByBeneficiary method, Request.
	/// Code Generated by IMS on: 1/11/2019 8:39:11 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISfclbybenefindClaimsByBeneficiaryRequest : VEISEcRequestBase
	{
		[DataMember]
		public Guid RelatedParentId { get; set; }
		[DataMember]
		public string RelatedParentEntityName { get; set; }
		[DataMember]
		public string RelatedParentFieldName { get; set; }
		[DataMember]
		public bool LogTiming { get; set; }
		[DataMember]
		public bool LogSoap { get; set; }
		[DataMember]
		public bool Debug { get; set; }
		[DataMember]
		public LegacyHeaderInfo LegacyServiceHeaderInfo { get; set; }
		[DataMember]
		public string mcs_transactionid { get; set; }
		[DataMember]
		public VEISfclbybeneReqCPEClaimAdapterv2findClaimsByBeneficiaryRequest1 VEISfclbybeneReqCPEClaimAdapterv2findClaimsByBeneficiaryRequest1Info { get; set; }
	}
	[DataContract]
	public class VEISfclbybeneReqCPEClaimAdapterv2findClaimsByBeneficiaryRequest1
	{
		[DataMember]
		public VIMTfclbybeneReqpersonId VIMTfclbybeneReqpersonIdInfo { get; set; }
		[DataMember]
		public VIMTfclbybeneReqresponseFilter VIMTfclbybeneReqresponseFilterInfo { get; set; }
	}
	[DataContract]
	public class VIMTfclbybeneReqpersonId
	{
		[DataMember]
		public string mcs_bfn { get; set; }
		[DataMember]
		public string mcs_dfn { get; set; }
	}
	[DataContract]
	public class VIMTfclbybeneReqresponseFilter
	{
		[DataMember]
		public DateTime mcs_startDate { get; set; }
		[DataMember]
		public bool mcs_startDateSpecified { get; set; }
		[DataMember]
		public DateTime mcs_endDate { get; set; }
		[DataMember]
		public bool mcs_endDateSpecified { get; set; }
		[DataMember]
		public Int32 mcs_chunkSize { get; set; }
		[DataMember]
		public bool mcs_chunkSizeSpecified { get; set; }
		[DataMember]
		public Int32 mcs_chunkNumber { get; set; }
		[DataMember]
		public bool mcs_chunkNumberSpecified { get; set; }
	}
}
