using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.ClaimAdapterService.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.ClaimAdapterService,getClaimDetails method, Request.
	/// Code Generated by IMS on: 1/11/2019 8:45:20 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISgtclmdtlsgetClaimDetailsRequest : VEISEcRequestBase
	{
		[DataMember]
		public Guid RelatedParentId { get; set; }
		[DataMember]
		public string RelatedParentEntityName { get; set; }
		[DataMember]
		public string RelatedParentFieldName { get; set; }
		[DataMember]
		public bool LogTiming { get; set; }
		[DataMember]
		public bool LogSoap { get; set; }
		[DataMember]
		public bool Debug { get; set; }
		[DataMember]
		public LegacyHeaderInfo LegacyServiceHeaderInfo { get; set; }
		[DataMember]
		public string mcs_transactionid { get; set; }
		[DataMember]
		public VEISgtclmdtlsReqCPEClaimAdapterv2getClaimDetailsRequest1 VEISgtclmdtlsReqCPEClaimAdapterv2getClaimDetailsRequest1Info { get; set; }
	}
	[DataContract]
	public class VEISgtclmdtlsReqCPEClaimAdapterv2getClaimDetailsRequest1
	{
		[DataMember]
		public string mcs_claimNumber { get; set; }
	}
}
