using System;
using System.ComponentModel.Composition;
using System.Runtime.Serialization;
using UDO.LOB.Core;


//using Microsoft.Xrm.Sdk;
//using VRM.Integration.Servicebus.Core;
//using VRM.Integration.UDO.Messages;

/// <summary>
/// VIMT LOB Component for UDOcreateDenials,createDenials method, Response.
/// Code Generated by IMS on: 6/18/2015 5:14:24 PM
/// Version: 2015.06.02
/// </summary>
/// <param name=none></param>
/// <returns>none</returns>

namespace UDO.LOB.Denials.Messages
{
    //[Export(typeof(IMessageBase))]
    //[ExportMetadata("MessageType", MessageRegistry.UDOcreateDenialsResponse)]
    [DataContract]
    public class UDOcreateDenialsResponse : MessageBase
    {
        [DataMember]
        public bool ExceptionOccurred { get; set; }
        [DataMember]
        public string ExceptionMessage { get; set; }
        [DataMember]
        public UDOcreateDenialsMultipleResponse[] UDOcreateDenialsInfo { get; set; }
    }
    [DataContract]
    public class UDOcreateDenialsMultipleResponse
    {
        [DataMember]
        public Guid newUDOcreateDenialsId { get; set; }
    }
}