using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.FMCService.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.FMCService,GetvendorDetails method, Request.
	/// Code Generated by IMS on: 1/7/2019 8:07:50 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISTFMCgvdGetvendorDetailsRequest : VEISEcRequestBase
	{
		[DataMember]
		public Guid RelatedParentId { get; set; }
		[DataMember]
		public string RelatedParentEntityName { get; set; }
		[DataMember]
		public string RelatedParentFieldName { get; set; }
		[DataMember]
		public bool LogTiming { get; set; }
		[DataMember]
		public bool LogSoap { get; set; }
		[DataMember]
		public bool Debug { get; set; }
		[DataMember]
		public LegacyHeaderInfo LegacyServiceHeaderInfo { get; set; }
		[DataMember]
		public VEISTFMCgvdReqVendorFile VEISTFMCgvdReqVendorFileInfo { get; set; }
	}
	[DataContract]
	public class VEISTFMCgvdReqVendorFile
	{
		[DataMember]
		public string mcs_VendorCode { get; set; }
		[DataMember]
		public string mcs_VendorName { get; set; }
		[DataMember]
		public string mcs_Address1 { get; set; }
		[DataMember]
		public string mcs_Address2 { get; set; }
		[DataMember]
		public string mcs_City { get; set; }
		[DataMember]
		public string mcs_State { get; set; }
		[DataMember]
		public string mcs_Zip { get; set; }
		[DataMember]
		public string mcs_VendType { get; set; }
		[DataMember]
		public string mcs_VendTypeCat { get; set; }
		[DataMember]
		public string mcs_MiscVend { get; set; }
		[DataMember]
		public string mcs_GroupCkInd { get; set; }
		[DataMember]
		public string mcs_Phone { get; set; }
		[DataMember]
		public string mcs_Contact { get; set; }
		[DataMember]
		public string mcs_CustAcct { get; set; }
		[DataMember]
		public string mcs_Comments { get; set; }
		[DataMember]
		public string mcs_VendProvCode { get; set; }
		[DataMember]
		public string mcs_ARContact { get; set; }
		[DataMember]
		public string mcs_HomeSta { get; set; }
		[DataMember]
		public string mcs_PymtHold { get; set; }
		[DataMember]
		public string mcs_PayLag { get; set; }
		[DataMember]
		public string mcs_LastPayDate { get; set; }
		[DataMember]
		public string mcs_Vend1099 { get; set; }
		[DataMember]
		public string mcs_CreditCard { get; set; }
		[DataMember]
		public string mcs_GsaInd { get; set; }
		[DataMember]
		public string mcs_FedAgencyInd { get; set; }
		[DataMember]
		public string mcs_SSNTaxId { get; set; }
		[DataMember]
		public string mcs_MfgInd { get; set; }
		[DataMember]
		public string mcs_DeleteInd { get; set; }
		[DataMember]
		public string mcs_JobInd { get; set; }
		[DataMember]
		public string mcs_RetInd { get; set; }
		[DataMember]
		public string mcs_FacInd { get; set; }
		[DataMember]
		public string mcs_IndepInd { get; set; }
		[DataMember]
		public string mcs_MinInd { get; set; }
		[DataMember]
		public string mcs_WomenInd { get; set; }
		[DataMember]
		public string mcs_SmallBusInd { get; set; }
		[DataMember]
		public string mcs_IncInd { get; set; }
		[DataMember]
		public string mcs_PartInd { get; set; }
		[DataMember]
		public string mcs_MinBusInd { get; set; }
		[DataMember]
		public string mcs_EftFlag { get; set; }
		[DataMember]
		public string mcs_BankNumb { get; set; }
		[DataMember]
		public string mcs_BankName { get; set; }
		[DataMember]
		public string mcs_CorrBankNumb { get; set; }
		[DataMember]
		public string mcs_CorrBank { get; set; }
		[DataMember]
		public string mcs_AcctNumb { get; set; }
		[DataMember]
		public string mcs_BankAcctype { get; set; }
		[DataMember]
		public string mcs_BankCity { get; set; }
		[DataMember]
		public string mcs_BankState { get; set; }
		[DataMember]
		public string mcs_BankZip { get; set; }
		[DataMember]
		public string mcs_GrpBills { get; set; }
		[DataMember]
		public string mcs_GroupDunning { get; set; }
		[DataMember]
		public string mcs_CustomerType { get; set; }
		[DataMember]
		public string mcs_VendorNameXref { get; set; }
		[DataMember]
		public string mcs_CustRefNo { get; set; }
		[DataMember]
		public string mcs_ActiveVendorId { get; set; }
		[DataMember]
		public string mcs_PromptPayType { get; set; }
		[DataMember]
		public string mcs_csn { get; set; }
		[DataMember]
		public string mcs_SSNTaxIdInd { get; set; }
		[DataMember]
		public string mcs_CentralRemit { get; set; }
		[DataMember]
		public string mcs_ACPayInd { get; set; }
		[DataMember]
		public string mcs_Levy { get; set; }
		[DataMember]
		public string mcs_CorrInd1099 { get; set; }
		[DataMember]
		public string mcs_LastActDate { get; set; }
		[DataMember]
		public string mcs_FactsDeptId { get; set; }
		[DataMember]
		public string mcs_FactBureauId { get; set; }
		[DataMember]
		public string mcs_DunsNumber { get; set; }
		[DataMember]
		public string mcs_CageCode { get; set; }
		[DataMember]
		public string mcs_CCRStatus { get; set; }
		[DataMember]
		public string mcs_npi { get; set; }
		[DataMember]
		public string mcs_Email { get; set; }
		[DataMember]
		public bool mcs_EdiVendor { get; set; }
		[DataMember]
		public bool mcs_EdiVendorSpecified { get; set; }
		[DataMember]
		public string mcs_VendorNameSearch { get; set; }
	}
}
