using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.BeneficiaryAdapterService.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.BeneficiaryAdapterService,getHouseholdData method, Request.
	/// Code Generated by IMS on: 1/11/2019 8:29:47 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISgCPEHDatgetHouseholdDataRequest : VEISEcRequestBase
	{
		[DataMember]
		public Guid RelatedParentId { get; set; }
		[DataMember]
		public string RelatedParentEntityName { get; set; }
		[DataMember]
		public string RelatedParentFieldName { get; set; }
		[DataMember]
		public bool LogTiming { get; set; }
		[DataMember]
		public bool LogSoap { get; set; }
		[DataMember]
		public bool Debug { get; set; }
		[DataMember]
		public LegacyHeaderInfo LegacyServiceHeaderInfo { get; set; }
		[DataMember]
		public string mcs_transactionid { get; set; }
		[DataMember]
		public VEISgCPEHDatReqCPEBeneficiaryAdapterv2getHouseholdDataRequest1 VEISgCPEHDatReqCPEBeneficiaryAdapterv2getHouseholdDataRequest1Info { get; set; }
	}
	[DataContract]
	public class VEISgCPEHDatReqCPEBeneficiaryAdapterv2getHouseholdDataRequest1
	{
		[DataMember]
		public VIMTgCPEHDatReqbeneficiaryIdentifier VIMTgCPEHDatReqbeneficiaryIdentifierInfo { get; set; }
	}
	[DataContract]
	public class VIMTgCPEHDatReqbeneficiaryIdentifier
	{
		[DataMember]
		public string mcs_bfn { get; set; }
		[DataMember]
		public string mcs_dfn { get; set; }
	}
}
