using System;
using System.Runtime.Serialization;
using UDO.LOB.Core;

//using Microsoft.Xrm.Sdk;
//using VRM.Integration.Servicebus.Core;
//using VRM.Integration.UDO.Messages;

/// <summary>
/// VIMT LOB Component for UDOcreateUDOSuspense,createUDOSuspense method, Response.
/// Code Generated by IMS on: 8/27/2015 2:42:59 PM
/// Version: 2015.06.02
/// </summary>
/// <param name=none></param>
/// <returns>none</returns>

namespace UDO.LOB.Claims.Messages
{
    //[Export(typeof(IMessageBase))]
    //[ExportMetadata("MessageType", MessageRegistry.UDOcreateUDOSuspenseResponse)]
    [DataContract]
    public class UDOcreateUDOSuspenseResponse : MessageBase
    {
        [DataMember]
        public bool ExceptionOccured { get; set; }
        [DataMember]
        public string ExceptionMessage { get; set; }
        [DataMember]
        public UDOcreateUDOSuspenseMultipleResponse[] UDOcreateUDOSuspenseInfo { get; set; }
    }
    [DataContract]
    public class UDOcreateUDOSuspenseMultipleResponse
    {
        [DataMember]
        public Guid newUDOcreateUDOSuspenseId { get; set; }
    }
}