//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crm.Plugins.IntentToFile.IntentToFileServiceReference {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intenttofile.services.vetsnet.vba.va.gov/")]
    public partial class messageFaultInfoBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intenttofile.services.vetsnet.vba.va.gov/")]
    public partial class intentToFileDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string badAddrsIndField;
        
        private long bnftClaimIdField;
        
        private bool bnftClaimIdFieldSpecified;
        
        private string clmantAddrsOneTxtField;
        
        private string clmantAddrsTwoTxtField;
        
        private string clmantAddrsUnitNbrField;
        
        private string clmantCityNmField;
        
        private string clmantCntryNmField;
        
        private string clmantEmailAddrsTxtField;
        
        private string clmantFirstNmField;
        
        private string clmantLastNmField;
        
        private string clmantMiddleNmField;
        
        private string clmantPhoneAreaNbrField;
        
        private string clmantPhoneNbrField;
        
        private string clmantSsnField;
        
        private string clmantStateCdField;
        
        private string clmantZipCdField;
        
        private System.DateTime cmpltdDtField;
        
        private bool cmpltdDtFieldSpecified;
        
        private System.DateTime createDtField;
        
        private bool createDtFieldSpecified;
        
        private string everFiledIndField;
        
        private System.DateTime exprtnDtField;
        
        private bool exprtnDtFieldSpecified;
        
        private string genderCdField;
        
        private string incompReasonTypeCdField;
        
        private long intentToFileIdField;
        
        private bool intentToFileIdFieldSpecified;
        
        private string itfStatusTypeCdField;
        
        private string itfTypeCdField;
        
        private System.DateTime jrnDtField;
        
        private bool jrnDtFieldSpecified;
        
        private string jrnExtnlApplcnNmField;
        
        private string jrnExtnlKeyTxtField;
        
        private string jrnExtnlUserIdField;
        
        private string jrnLctnIdField;
        
        private string jrnObjIdField;
        
        private string jrnStatusTypeCdField;
        
        private string jrnUserIdField;
        
        private long ptcpntClmantIdField;
        
        private bool ptcpntClmantIdFieldSpecified;
        
        private long ptcpntVetIdField;
        
        private bool ptcpntVetIdFieldSpecified;
        
        private System.DateTime rcvdDtField;
        
        private bool rcvdDtFieldSpecified;
        
        private System.DateTime signedDtField;
        
        private bool signedDtFieldSpecified;
        
        private string signtrIndField;
        
        private System.DateTime submtdDtField;
        
        private bool submtdDtFieldSpecified;
        
        private string submtrApplcnTypeCdField;
        
        private long submtrPtcpntIdField;
        
        private bool submtrPtcpntIdFieldSpecified;
        
        private string supresLetterIndField;
        
        private System.DateTime vetBrthdyDtField;
        
        private bool vetBrthdyDtFieldSpecified;
        
        private string vetFileNbrField;
        
        private string vetFirstNmField;
        
        private string vetLastNmField;
        
        private string vetMiddleNmField;
        
        private string vetSsnNbrField;
        
        private string vsoNmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string badAddrsInd {
            get {
                return this.badAddrsIndField;
            }
            set {
                this.badAddrsIndField = value;
                this.RaisePropertyChanged("badAddrsInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long bnftClaimId {
            get {
                return this.bnftClaimIdField;
            }
            set {
                this.bnftClaimIdField = value;
                this.RaisePropertyChanged("bnftClaimId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bnftClaimIdSpecified {
            get {
                return this.bnftClaimIdFieldSpecified;
            }
            set {
                this.bnftClaimIdFieldSpecified = value;
                this.RaisePropertyChanged("bnftClaimIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string clmantAddrsOneTxt {
            get {
                return this.clmantAddrsOneTxtField;
            }
            set {
                this.clmantAddrsOneTxtField = value;
                this.RaisePropertyChanged("clmantAddrsOneTxt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string clmantAddrsTwoTxt {
            get {
                return this.clmantAddrsTwoTxtField;
            }
            set {
                this.clmantAddrsTwoTxtField = value;
                this.RaisePropertyChanged("clmantAddrsTwoTxt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string clmantAddrsUnitNbr {
            get {
                return this.clmantAddrsUnitNbrField;
            }
            set {
                this.clmantAddrsUnitNbrField = value;
                this.RaisePropertyChanged("clmantAddrsUnitNbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string clmantCityNm {
            get {
                return this.clmantCityNmField;
            }
            set {
                this.clmantCityNmField = value;
                this.RaisePropertyChanged("clmantCityNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string clmantCntryNm {
            get {
                return this.clmantCntryNmField;
            }
            set {
                this.clmantCntryNmField = value;
                this.RaisePropertyChanged("clmantCntryNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string clmantEmailAddrsTxt {
            get {
                return this.clmantEmailAddrsTxtField;
            }
            set {
                this.clmantEmailAddrsTxtField = value;
                this.RaisePropertyChanged("clmantEmailAddrsTxt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string clmantFirstNm {
            get {
                return this.clmantFirstNmField;
            }
            set {
                this.clmantFirstNmField = value;
                this.RaisePropertyChanged("clmantFirstNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string clmantLastNm {
            get {
                return this.clmantLastNmField;
            }
            set {
                this.clmantLastNmField = value;
                this.RaisePropertyChanged("clmantLastNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string clmantMiddleNm {
            get {
                return this.clmantMiddleNmField;
            }
            set {
                this.clmantMiddleNmField = value;
                this.RaisePropertyChanged("clmantMiddleNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string clmantPhoneAreaNbr {
            get {
                return this.clmantPhoneAreaNbrField;
            }
            set {
                this.clmantPhoneAreaNbrField = value;
                this.RaisePropertyChanged("clmantPhoneAreaNbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string clmantPhoneNbr {
            get {
                return this.clmantPhoneNbrField;
            }
            set {
                this.clmantPhoneNbrField = value;
                this.RaisePropertyChanged("clmantPhoneNbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string clmantSsn {
            get {
                return this.clmantSsnField;
            }
            set {
                this.clmantSsnField = value;
                this.RaisePropertyChanged("clmantSsn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string clmantStateCd {
            get {
                return this.clmantStateCdField;
            }
            set {
                this.clmantStateCdField = value;
                this.RaisePropertyChanged("clmantStateCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string clmantZipCd {
            get {
                return this.clmantZipCdField;
            }
            set {
                this.clmantZipCdField = value;
                this.RaisePropertyChanged("clmantZipCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public System.DateTime cmpltdDt {
            get {
                return this.cmpltdDtField;
            }
            set {
                this.cmpltdDtField = value;
                this.RaisePropertyChanged("cmpltdDt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cmpltdDtSpecified {
            get {
                return this.cmpltdDtFieldSpecified;
            }
            set {
                this.cmpltdDtFieldSpecified = value;
                this.RaisePropertyChanged("cmpltdDtSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public System.DateTime createDt {
            get {
                return this.createDtField;
            }
            set {
                this.createDtField = value;
                this.RaisePropertyChanged("createDt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createDtSpecified {
            get {
                return this.createDtFieldSpecified;
            }
            set {
                this.createDtFieldSpecified = value;
                this.RaisePropertyChanged("createDtSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string everFiledInd {
            get {
                return this.everFiledIndField;
            }
            set {
                this.everFiledIndField = value;
                this.RaisePropertyChanged("everFiledInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public System.DateTime exprtnDt {
            get {
                return this.exprtnDtField;
            }
            set {
                this.exprtnDtField = value;
                this.RaisePropertyChanged("exprtnDt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool exprtnDtSpecified {
            get {
                return this.exprtnDtFieldSpecified;
            }
            set {
                this.exprtnDtFieldSpecified = value;
                this.RaisePropertyChanged("exprtnDtSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string genderCd {
            get {
                return this.genderCdField;
            }
            set {
                this.genderCdField = value;
                this.RaisePropertyChanged("genderCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string incompReasonTypeCd {
            get {
                return this.incompReasonTypeCdField;
            }
            set {
                this.incompReasonTypeCdField = value;
                this.RaisePropertyChanged("incompReasonTypeCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public long intentToFileId {
            get {
                return this.intentToFileIdField;
            }
            set {
                this.intentToFileIdField = value;
                this.RaisePropertyChanged("intentToFileId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool intentToFileIdSpecified {
            get {
                return this.intentToFileIdFieldSpecified;
            }
            set {
                this.intentToFileIdFieldSpecified = value;
                this.RaisePropertyChanged("intentToFileIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string itfStatusTypeCd {
            get {
                return this.itfStatusTypeCdField;
            }
            set {
                this.itfStatusTypeCdField = value;
                this.RaisePropertyChanged("itfStatusTypeCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string itfTypeCd {
            get {
                return this.itfTypeCdField;
            }
            set {
                this.itfTypeCdField = value;
                this.RaisePropertyChanged("itfTypeCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public System.DateTime jrnDt {
            get {
                return this.jrnDtField;
            }
            set {
                this.jrnDtField = value;
                this.RaisePropertyChanged("jrnDt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool jrnDtSpecified {
            get {
                return this.jrnDtFieldSpecified;
            }
            set {
                this.jrnDtFieldSpecified = value;
                this.RaisePropertyChanged("jrnDtSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string jrnExtnlApplcnNm {
            get {
                return this.jrnExtnlApplcnNmField;
            }
            set {
                this.jrnExtnlApplcnNmField = value;
                this.RaisePropertyChanged("jrnExtnlApplcnNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string jrnExtnlKeyTxt {
            get {
                return this.jrnExtnlKeyTxtField;
            }
            set {
                this.jrnExtnlKeyTxtField = value;
                this.RaisePropertyChanged("jrnExtnlKeyTxt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string jrnExtnlUserId {
            get {
                return this.jrnExtnlUserIdField;
            }
            set {
                this.jrnExtnlUserIdField = value;
                this.RaisePropertyChanged("jrnExtnlUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string jrnLctnId {
            get {
                return this.jrnLctnIdField;
            }
            set {
                this.jrnLctnIdField = value;
                this.RaisePropertyChanged("jrnLctnId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string jrnObjId {
            get {
                return this.jrnObjIdField;
            }
            set {
                this.jrnObjIdField = value;
                this.RaisePropertyChanged("jrnObjId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string jrnStatusTypeCd {
            get {
                return this.jrnStatusTypeCdField;
            }
            set {
                this.jrnStatusTypeCdField = value;
                this.RaisePropertyChanged("jrnStatusTypeCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string jrnUserId {
            get {
                return this.jrnUserIdField;
            }
            set {
                this.jrnUserIdField = value;
                this.RaisePropertyChanged("jrnUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public long ptcpntClmantId {
            get {
                return this.ptcpntClmantIdField;
            }
            set {
                this.ptcpntClmantIdField = value;
                this.RaisePropertyChanged("ptcpntClmantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ptcpntClmantIdSpecified {
            get {
                return this.ptcpntClmantIdFieldSpecified;
            }
            set {
                this.ptcpntClmantIdFieldSpecified = value;
                this.RaisePropertyChanged("ptcpntClmantIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public long ptcpntVetId {
            get {
                return this.ptcpntVetIdField;
            }
            set {
                this.ptcpntVetIdField = value;
                this.RaisePropertyChanged("ptcpntVetId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ptcpntVetIdSpecified {
            get {
                return this.ptcpntVetIdFieldSpecified;
            }
            set {
                this.ptcpntVetIdFieldSpecified = value;
                this.RaisePropertyChanged("ptcpntVetIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public System.DateTime rcvdDt {
            get {
                return this.rcvdDtField;
            }
            set {
                this.rcvdDtField = value;
                this.RaisePropertyChanged("rcvdDt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rcvdDtSpecified {
            get {
                return this.rcvdDtFieldSpecified;
            }
            set {
                this.rcvdDtFieldSpecified = value;
                this.RaisePropertyChanged("rcvdDtSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public System.DateTime signedDt {
            get {
                return this.signedDtField;
            }
            set {
                this.signedDtField = value;
                this.RaisePropertyChanged("signedDt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool signedDtSpecified {
            get {
                return this.signedDtFieldSpecified;
            }
            set {
                this.signedDtFieldSpecified = value;
                this.RaisePropertyChanged("signedDtSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string signtrInd {
            get {
                return this.signtrIndField;
            }
            set {
                this.signtrIndField = value;
                this.RaisePropertyChanged("signtrInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public System.DateTime submtdDt {
            get {
                return this.submtdDtField;
            }
            set {
                this.submtdDtField = value;
                this.RaisePropertyChanged("submtdDt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool submtdDtSpecified {
            get {
                return this.submtdDtFieldSpecified;
            }
            set {
                this.submtdDtFieldSpecified = value;
                this.RaisePropertyChanged("submtdDtSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string submtrApplcnTypeCd {
            get {
                return this.submtrApplcnTypeCdField;
            }
            set {
                this.submtrApplcnTypeCdField = value;
                this.RaisePropertyChanged("submtrApplcnTypeCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public long submtrPtcpntId {
            get {
                return this.submtrPtcpntIdField;
            }
            set {
                this.submtrPtcpntIdField = value;
                this.RaisePropertyChanged("submtrPtcpntId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool submtrPtcpntIdSpecified {
            get {
                return this.submtrPtcpntIdFieldSpecified;
            }
            set {
                this.submtrPtcpntIdFieldSpecified = value;
                this.RaisePropertyChanged("submtrPtcpntIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string supresLetterInd {
            get {
                return this.supresLetterIndField;
            }
            set {
                this.supresLetterIndField = value;
                this.RaisePropertyChanged("supresLetterInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public System.DateTime vetBrthdyDt {
            get {
                return this.vetBrthdyDtField;
            }
            set {
                this.vetBrthdyDtField = value;
                this.RaisePropertyChanged("vetBrthdyDt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vetBrthdyDtSpecified {
            get {
                return this.vetBrthdyDtFieldSpecified;
            }
            set {
                this.vetBrthdyDtFieldSpecified = value;
                this.RaisePropertyChanged("vetBrthdyDtSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string vetFileNbr {
            get {
                return this.vetFileNbrField;
            }
            set {
                this.vetFileNbrField = value;
                this.RaisePropertyChanged("vetFileNbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string vetFirstNm {
            get {
                return this.vetFirstNmField;
            }
            set {
                this.vetFirstNmField = value;
                this.RaisePropertyChanged("vetFirstNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string vetLastNm {
            get {
                return this.vetLastNmField;
            }
            set {
                this.vetLastNmField = value;
                this.RaisePropertyChanged("vetLastNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string vetMiddleNm {
            get {
                return this.vetMiddleNmField;
            }
            set {
                this.vetMiddleNmField = value;
                this.RaisePropertyChanged("vetMiddleNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string vetSsnNbr {
            get {
                return this.vetSsnNbrField;
            }
            set {
                this.vetSsnNbrField = value;
                this.RaisePropertyChanged("vetSsnNbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public string vsoNm {
            get {
                return this.vsoNmField;
            }
            set {
                this.vsoNmField = value;
                this.RaisePropertyChanged("vsoNm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://intenttofile.services.vetsnet.vba.va.gov/", ConfigurationName="IntentToFileServiceReference.IntentToFileWebService")]
    public interface IntentToFileWebService {
        
        // CODEGEN: Parameter 'IntentToFileDTO' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Crm.Plugins.IntentToFile.IntentToFileServiceReference.messageFaultInfoBean), Action="", Name="MessageException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="IntentToFileDTO")]
        Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdResponse findIntentToFileByPtcpntId(Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdResponse> findIntentToFileByPtcpntIdAsync(Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdRequest request);
        
        // CODEGEN: Parameter 'IntentToFileDTO' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Crm.Plugins.IntentToFile.IntentToFileServiceReference.messageFaultInfoBean), Action="", Name="MessageException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="IntentToFileDTO")]
        Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdResponse findIntentToFileByPtcpntIdItfTypeCd(Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdResponse> findIntentToFileByPtcpntIdItfTypeCdAsync(Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdRequest request);
        
        // CODEGEN: Parameter 'IntentToFileDTO' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Crm.Plugins.IntentToFile.IntentToFileServiceReference.messageFaultInfoBean), Action="", Name="MessageException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="IntentToFileDTO")]
        Crm.Plugins.IntentToFile.IntentToFileServiceReference.insertIntentToFileResponse insertIntentToFile(Crm.Plugins.IntentToFile.IntentToFileServiceReference.insertIntentToFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Crm.Plugins.IntentToFile.IntentToFileServiceReference.insertIntentToFileResponse> insertIntentToFileAsync(Crm.Plugins.IntentToFile.IntentToFileServiceReference.insertIntentToFileRequest request);
        
        // CODEGEN: Parameter 'IntentToFileDTO' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Crm.Plugins.IntentToFile.IntentToFileServiceReference.messageFaultInfoBean), Action="", Name="MessageException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="IntentToFileDTO")]
        Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdResponse findIntentToFileByPtcpntIdItfTypeCdBnftClaimId(Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdResponse> findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdAsync(Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findIntentToFileByPtcpntId", WrapperNamespace="http://intenttofile.services.vetsnet.vba.va.gov/", IsWrapped=true)]
    public partial class findIntentToFileByPtcpntIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intenttofile.services.vetsnet.vba.va.gov/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long ptcpntId;
        
        public findIntentToFileByPtcpntIdRequest() {
        }
        
        public findIntentToFileByPtcpntIdRequest(long ptcpntId) {
            this.ptcpntId = ptcpntId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findIntentToFileByPtcpntIdResponse", WrapperNamespace="http://intenttofile.services.vetsnet.vba.va.gov/", IsWrapped=true)]
    public partial class findIntentToFileByPtcpntIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intenttofile.services.vetsnet.vba.va.gov/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IntentToFileDTO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Crm.Plugins.IntentToFile.IntentToFileServiceReference.intentToFileDTO[] IntentToFileDTO;
        
        public findIntentToFileByPtcpntIdResponse() {
        }
        
        public findIntentToFileByPtcpntIdResponse(Crm.Plugins.IntentToFile.IntentToFileServiceReference.intentToFileDTO[] IntentToFileDTO) {
            this.IntentToFileDTO = IntentToFileDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findIntentToFileByPtcpntIdItfTypeCd", WrapperNamespace="http://intenttofile.services.vetsnet.vba.va.gov/", IsWrapped=true)]
    public partial class findIntentToFileByPtcpntIdItfTypeCdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intenttofile.services.vetsnet.vba.va.gov/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long ptcpntId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intenttofile.services.vetsnet.vba.va.gov/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string itfTypeCd;
        
        public findIntentToFileByPtcpntIdItfTypeCdRequest() {
        }
        
        public findIntentToFileByPtcpntIdItfTypeCdRequest(long ptcpntId, string itfTypeCd) {
            this.ptcpntId = ptcpntId;
            this.itfTypeCd = itfTypeCd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findIntentToFileByPtcpntIdItfTypeCdResponse", WrapperNamespace="http://intenttofile.services.vetsnet.vba.va.gov/", IsWrapped=true)]
    public partial class findIntentToFileByPtcpntIdItfTypeCdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intenttofile.services.vetsnet.vba.va.gov/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IntentToFileDTO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Crm.Plugins.IntentToFile.IntentToFileServiceReference.intentToFileDTO[] IntentToFileDTO;
        
        public findIntentToFileByPtcpntIdItfTypeCdResponse() {
        }
        
        public findIntentToFileByPtcpntIdItfTypeCdResponse(Crm.Plugins.IntentToFile.IntentToFileServiceReference.intentToFileDTO[] IntentToFileDTO) {
            this.IntentToFileDTO = IntentToFileDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertIntentToFile", WrapperNamespace="http://intenttofile.services.vetsnet.vba.va.gov/", IsWrapped=true)]
    public partial class insertIntentToFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intenttofile.services.vetsnet.vba.va.gov/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Crm.Plugins.IntentToFile.IntentToFileServiceReference.intentToFileDTO intentToFileDTO;
        
        public insertIntentToFileRequest() {
        }
        
        public insertIntentToFileRequest(Crm.Plugins.IntentToFile.IntentToFileServiceReference.intentToFileDTO intentToFileDTO) {
            this.intentToFileDTO = intentToFileDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertIntentToFileResponse", WrapperNamespace="http://intenttofile.services.vetsnet.vba.va.gov/", IsWrapped=true)]
    public partial class insertIntentToFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intenttofile.services.vetsnet.vba.va.gov/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Crm.Plugins.IntentToFile.IntentToFileServiceReference.intentToFileDTO IntentToFileDTO;
        
        public insertIntentToFileResponse() {
        }
        
        public insertIntentToFileResponse(Crm.Plugins.IntentToFile.IntentToFileServiceReference.intentToFileDTO IntentToFileDTO) {
            this.IntentToFileDTO = IntentToFileDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findIntentToFileByPtcpntIdItfTypeCdBnftClaimId", WrapperNamespace="http://intenttofile.services.vetsnet.vba.va.gov/", IsWrapped=true)]
    public partial class findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intenttofile.services.vetsnet.vba.va.gov/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long ptcpntId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intenttofile.services.vetsnet.vba.va.gov/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string itfTypeCd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intenttofile.services.vetsnet.vba.va.gov/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long bnftClaimId;
        
        public findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdRequest() {
        }
        
        public findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdRequest(long ptcpntId, string itfTypeCd, long bnftClaimId) {
            this.ptcpntId = ptcpntId;
            this.itfTypeCd = itfTypeCd;
            this.bnftClaimId = bnftClaimId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdResponse", WrapperNamespace="http://intenttofile.services.vetsnet.vba.va.gov/", IsWrapped=true)]
    public partial class findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intenttofile.services.vetsnet.vba.va.gov/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IntentToFileDTO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Crm.Plugins.IntentToFile.IntentToFileServiceReference.intentToFileDTO[] IntentToFileDTO;
        
        public findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdResponse() {
        }
        
        public findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdResponse(Crm.Plugins.IntentToFile.IntentToFileServiceReference.intentToFileDTO[] IntentToFileDTO) {
            this.IntentToFileDTO = IntentToFileDTO;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IntentToFileWebServiceChannel : Crm.Plugins.IntentToFile.IntentToFileServiceReference.IntentToFileWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntentToFileWebServiceClient : System.ServiceModel.ClientBase<Crm.Plugins.IntentToFile.IntentToFileServiceReference.IntentToFileWebService>, Crm.Plugins.IntentToFile.IntentToFileServiceReference.IntentToFileWebService {
        
        public IntentToFileWebServiceClient() {
        }
        
        public IntentToFileWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntentToFileWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntentToFileWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntentToFileWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdResponse Crm.Plugins.IntentToFile.IntentToFileServiceReference.IntentToFileWebService.findIntentToFileByPtcpntId(Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdRequest request) {
            return base.Channel.findIntentToFileByPtcpntId(request);
        }
        
        public Crm.Plugins.IntentToFile.IntentToFileServiceReference.intentToFileDTO[] findIntentToFileByPtcpntId(long ptcpntId) {
            Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdRequest inValue = new Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdRequest();
            inValue.ptcpntId = ptcpntId;
            Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdResponse retVal = ((Crm.Plugins.IntentToFile.IntentToFileServiceReference.IntentToFileWebService)(this)).findIntentToFileByPtcpntId(inValue);
            return retVal.IntentToFileDTO;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdResponse> Crm.Plugins.IntentToFile.IntentToFileServiceReference.IntentToFileWebService.findIntentToFileByPtcpntIdAsync(Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdRequest request) {
            return base.Channel.findIntentToFileByPtcpntIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdResponse> findIntentToFileByPtcpntIdAsync(long ptcpntId) {
            Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdRequest inValue = new Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdRequest();
            inValue.ptcpntId = ptcpntId;
            return ((Crm.Plugins.IntentToFile.IntentToFileServiceReference.IntentToFileWebService)(this)).findIntentToFileByPtcpntIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdResponse Crm.Plugins.IntentToFile.IntentToFileServiceReference.IntentToFileWebService.findIntentToFileByPtcpntIdItfTypeCd(Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdRequest request) {
            return base.Channel.findIntentToFileByPtcpntIdItfTypeCd(request);
        }
        
        public Crm.Plugins.IntentToFile.IntentToFileServiceReference.intentToFileDTO[] findIntentToFileByPtcpntIdItfTypeCd(long ptcpntId, string itfTypeCd) {
            Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdRequest inValue = new Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdRequest();
            inValue.ptcpntId = ptcpntId;
            inValue.itfTypeCd = itfTypeCd;
            Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdResponse retVal = ((Crm.Plugins.IntentToFile.IntentToFileServiceReference.IntentToFileWebService)(this)).findIntentToFileByPtcpntIdItfTypeCd(inValue);
            return retVal.IntentToFileDTO;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdResponse> Crm.Plugins.IntentToFile.IntentToFileServiceReference.IntentToFileWebService.findIntentToFileByPtcpntIdItfTypeCdAsync(Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdRequest request) {
            return base.Channel.findIntentToFileByPtcpntIdItfTypeCdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdResponse> findIntentToFileByPtcpntIdItfTypeCdAsync(long ptcpntId, string itfTypeCd) {
            Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdRequest inValue = new Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdRequest();
            inValue.ptcpntId = ptcpntId;
            inValue.itfTypeCd = itfTypeCd;
            return ((Crm.Plugins.IntentToFile.IntentToFileServiceReference.IntentToFileWebService)(this)).findIntentToFileByPtcpntIdItfTypeCdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Crm.Plugins.IntentToFile.IntentToFileServiceReference.insertIntentToFileResponse Crm.Plugins.IntentToFile.IntentToFileServiceReference.IntentToFileWebService.insertIntentToFile(Crm.Plugins.IntentToFile.IntentToFileServiceReference.insertIntentToFileRequest request) {
            return base.Channel.insertIntentToFile(request);
        }
        
        public Crm.Plugins.IntentToFile.IntentToFileServiceReference.intentToFileDTO insertIntentToFile(Crm.Plugins.IntentToFile.IntentToFileServiceReference.intentToFileDTO intentToFileDTO) {
            Crm.Plugins.IntentToFile.IntentToFileServiceReference.insertIntentToFileRequest inValue = new Crm.Plugins.IntentToFile.IntentToFileServiceReference.insertIntentToFileRequest();
            inValue.intentToFileDTO = intentToFileDTO;
            Crm.Plugins.IntentToFile.IntentToFileServiceReference.insertIntentToFileResponse retVal = ((Crm.Plugins.IntentToFile.IntentToFileServiceReference.IntentToFileWebService)(this)).insertIntentToFile(inValue);
            return retVal.IntentToFileDTO;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Crm.Plugins.IntentToFile.IntentToFileServiceReference.insertIntentToFileResponse> Crm.Plugins.IntentToFile.IntentToFileServiceReference.IntentToFileWebService.insertIntentToFileAsync(Crm.Plugins.IntentToFile.IntentToFileServiceReference.insertIntentToFileRequest request) {
            return base.Channel.insertIntentToFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<Crm.Plugins.IntentToFile.IntentToFileServiceReference.insertIntentToFileResponse> insertIntentToFileAsync(Crm.Plugins.IntentToFile.IntentToFileServiceReference.intentToFileDTO intentToFileDTO) {
            Crm.Plugins.IntentToFile.IntentToFileServiceReference.insertIntentToFileRequest inValue = new Crm.Plugins.IntentToFile.IntentToFileServiceReference.insertIntentToFileRequest();
            inValue.intentToFileDTO = intentToFileDTO;
            return ((Crm.Plugins.IntentToFile.IntentToFileServiceReference.IntentToFileWebService)(this)).insertIntentToFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdResponse Crm.Plugins.IntentToFile.IntentToFileServiceReference.IntentToFileWebService.findIntentToFileByPtcpntIdItfTypeCdBnftClaimId(Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdRequest request) {
            return base.Channel.findIntentToFileByPtcpntIdItfTypeCdBnftClaimId(request);
        }
        
        public Crm.Plugins.IntentToFile.IntentToFileServiceReference.intentToFileDTO[] findIntentToFileByPtcpntIdItfTypeCdBnftClaimId(long ptcpntId, string itfTypeCd, long bnftClaimId) {
            Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdRequest inValue = new Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdRequest();
            inValue.ptcpntId = ptcpntId;
            inValue.itfTypeCd = itfTypeCd;
            inValue.bnftClaimId = bnftClaimId;
            Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdResponse retVal = ((Crm.Plugins.IntentToFile.IntentToFileServiceReference.IntentToFileWebService)(this)).findIntentToFileByPtcpntIdItfTypeCdBnftClaimId(inValue);
            return retVal.IntentToFileDTO;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdResponse> Crm.Plugins.IntentToFile.IntentToFileServiceReference.IntentToFileWebService.findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdAsync(Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdRequest request) {
            return base.Channel.findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdResponse> findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdAsync(long ptcpntId, string itfTypeCd, long bnftClaimId) {
            Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdRequest inValue = new Crm.Plugins.IntentToFile.IntentToFileServiceReference.findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdRequest();
            inValue.ptcpntId = ptcpntId;
            inValue.itfTypeCd = itfTypeCd;
            inValue.bnftClaimId = bnftClaimId;
            return ((Crm.Plugins.IntentToFile.IntentToFileServiceReference.IntentToFileWebService)(this)).findIntentToFileByPtcpntIdItfTypeCdBnftClaimIdAsync(inValue);
        }
    }
}
