using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.DevelopmentNotesService.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.DevelopmentNotesService,updateNote method, Request.
	/// Code Generated by IMS on: 12/21/2018 2:15:27 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISupdateupdateNoteRequest : VEISEcRequestBase
	{
		[DataMember]
		public Guid RelatedParentId { get; set; }
		[DataMember]
		public string RelatedParentEntityName { get; set; }
		[DataMember]
		public string RelatedParentFieldName { get; set; }
		[DataMember]
		public bool LogTiming { get; set; }
		[DataMember]
		public bool LogSoap { get; set; }
		[DataMember]
		public bool Debug { get; set; }
		[DataMember]
		public LegacyHeaderInfo LegacyServiceHeaderInfo { get; set; }
		[DataMember]
		public VEISupdateReqnote VEISupdateReqnoteInfo { get; set; }
	}
	[DataContract]
	public class VEISupdateReqnote
	{
	}
}
