using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.DevelopmentNotesService.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.DevelopmentNotesService,updateNote method, Response.
	/// Code Generated by IMS on: 12/21/2018 2:15:27 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISupdateupdateNoteResponse : VEISEcResponseBase
	{
		[DataMember]
		public VEISupdateVoid VEISupdateVoidInfo { get; set; }
	}
	[DataContract]
	public class VEISupdateVoid
	{
	}
}
