using System;
using Microsoft.Xrm.Sdk;
using System.ComponentModel.Composition;
using System.Runtime.Serialization;
using VRM.Integration.Servicebus.Core;
using VRM.Integration.UDO.Messages;
/// <summary>
/// VIMT LOB Component for UDOcreatePaymentAdjustments,createPaymentAdjustments method, Response.
/// Code Generated by IMS on: 6/4/2015 9:25:46 AM
/// Version: 2015.06.02
/// </summary>
/// <param name=none></param>
/// <returns>none</returns>

namespace VRM.Integration.UDO.Payments.Messages
{
    [Export(typeof(IMessageBase))]
    [ExportMetadata("MessageType", MessageRegistry.UDOcreatePaymentAdjustmentsResponse)]
    [DataContract]
    public class UDOcreatePaymentAdjustmentsResponse : MessageBase
    {
        [DataMember]
        public bool ExceptionOccured { get; set; }
        [DataMember]
        public string ExceptionMessage { get; set; }
        [DataMember]
        public UDOcreatePaymentAdjustmentsMultipleResponse[] UDOcreatePaymentAdjustmentsInfo { get; set; }
    }
    [DataContract]
    public class UDOcreatePaymentAdjustmentsMultipleResponse
    {
        [DataMember]
        public Guid newUDOcreatePaymentAdjustmentsId { get; set; }
    }
}