using System;
using Microsoft.Xrm.Sdk;
using System.ComponentModel.Composition;
using System.Runtime.Serialization;
using VRM.Integration.Servicebus.Core;
using VRM.Integration.UDO.Messages;

/// <summary>
/// VIMT LOB Component for UDOgetPaymentDetails,getPaymentDetails method, Response.
/// Code Generated by IMS on: 6/4/2015 1:39:18 PM
/// Version: 2015.06.02
/// </summary>
/// <param name=none></param>
/// <returns>none</returns>

namespace VRM.Integration.UDO.Payments.Messages
{
    [Export(typeof(IMessageBase))]
    [ExportMetadata("MessageType", MessageRegistry.UDOgetPaymentDetailsResponse)]
    [DataContract]
    public class UDOgetPaymentDetailsResponse : MessageBase
    {
        [DataMember]
        public bool ExceptionOccured { get; set; }
        [DataMember]
        public string ExceptionMessage { get; set; }
        [DataMember]
        public UDOgetPaymentDetails UDOgetPaymentDetailsInfo { get; set; }
        [DataMember]
        public UDOgetPaymentAdjustmentsMultipleResponse[] UDOgetPaymentAdjustmentsMultipleResponse { get; set; }
        [DataMember]
        public UDOgetAwardAdjustmentsMultipleResponse[] UDOgetAwardAdjustmentsMultipleResponse { get; set; }
        [DataMember]
        public UDOgetAwardReasonsMultipleResponse[] UDOgetAwardReasonsMultipleResponse { get; set; }
    }
    [DataContract]
    public class UDOgetPaymentDetails
    {
        [DataMember]
        public string udo_TransactionID { get; set; }
        [DataMember]
        public DateTime udo_ScheduledDate { get; set; }
        [DataMember]
        public string udo_RoutingNumber { get; set; }
        [DataMember]
        public string udo_RO { get; set; }
        [DataMember]
        public string udo_ReturnPayment { get; set; }
        [DataMember]
        public string udo_Recipient { get; set; }
        [DataMember]
        public string udo_Reason { get; set; }
        [DataMember]
        public string udo_ProgramType { get; set; }
        [DataMember]
        public string udo_ProcessingStation { get; set; }
        [DataMember]
        public string udo_PaymentType { get; set; }
        [DataMember]
        public string udo_PaymentMessage { get; set; }
        [DataMember]
        public string udo_PaymentIdentifier { get; set; }
        [DataMember]
        public bool udo_PaymentCompleteFlag { get; set; }
        [DataMember]
        public string udo_PayeeType { get; set; }
        [DataMember]
        public DateTime udo_PayDate { get; set; }
        [DataMember]
        public string udo_NetPaymentAmount { get; set; }
        [DataMember]
        public string udo_NetAwardAmount { get; set; }
        [DataMember]
        public int udo_LegacyPaymentId { get; set; }
        [DataMember]
        public string udo_GrossPaymentAmount { get; set; }
        [DataMember]
        public string udo_GrossAwardAmount { get; set; }
        [DataMember]
        public int udo_ftbid { get; set; }
        [DataMember]
        public string udo_BankName { get; set; }
        [DataMember]
        public DateTime udo_AwardEffectiveDate { get; set; }
        [DataMember]
        public DateTime udo_AuthorizedDate { get; set; }
        [DataMember]
        public string udo_Amount { get; set; }
        [DataMember]
        public string udo_Address { get; set; }
        [DataMember]
        public string udo_AccountType { get; set; }
        [DataMember]
        public string udo_AccountNumber { get; set; }
    }
    public class UDOgetPaymentAdjustmentsMultipleResponse
    {
        [DataMember]
        public Guid newUDOcreatePaymentAdjustmentsId { get; set; }
    }

    public class UDOgetAwardAdjustmentsMultipleResponse
    {
        [DataMember]
        public Guid newUDOcreateAwardAdjustmentId { get; set; }
    }

    public class UDOgetAwardReasonsMultipleResponse
    {
        [DataMember]
        public Guid newUDOcreateAwardReasonId { get; set; }
    }
}