using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.VIAScheduling.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.VIAScheduling,getCancellationReasons method, Response.
	/// Code Generated by IMS on: 1/24/2019 5:36:16 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISVIASchedGCRgetCancellationReasonsResponse : VEISEcResponseBase
	{
		[DataMember]
		public VEISVIASchedGCRtaggedCancellationReasonsArray VEISVIASchedGCRtaggedCancellationReasonsArrayInfo { get; set; }
	}
	[DataContract]
	public class VEISVIASchedGCRtaggedCancellationReasonsArray
	{
		[DataMember]
		public string mcs_tag { get; set; }
		[DataMember]
		public Int32 mcs_count { get; set; }
		[DataMember]
		public bool mcs_countSpecified { get; set; }
		[DataMember]
		public VEISVIASchedGCRreasonsMultipleResponse[] VEISVIASchedGCRreasonsInfo { get; set; }
		[DataMember]
		public VEISVIASchedGCRfault1 VEISVIASchedGCRfault1Info { get; set; }
	}
	[DataContract]
	public class VEISVIASchedGCRreasonsMultipleResponse
	{
		[DataMember]
		public string mcs_id { get; set; }
		[DataMember]
		public string mcs_name { get; set; }
		[DataMember]
		public VEISVIASchedGCRfault VEISVIASchedGCRfaultInfo { get; set; }
	}
	[DataContract]
	public class VEISVIASchedGCRfault
	{
		[DataMember]
		public string mcs_innerMessage { get; set; }
		[DataMember]
		public string mcs_innerStackTrace { get; set; }
		[DataMember]
		public string mcs_innerType { get; set; }
		[DataMember]
		public string mcs_message { get; set; }
		[DataMember]
		public string mcs_stackTrace { get; set; }
		[DataMember]
		public string mcs_suggestion { get; set; }
		[DataMember]
		public string mcs_type { get; set; }
	}
	[DataContract]
	public class VEISVIASchedGCRfault1
	{
		[DataMember]
		public string mcs_innerMessage { get; set; }
		[DataMember]
		public string mcs_innerStackTrace { get; set; }
		[DataMember]
		public string mcs_innerType { get; set; }
		[DataMember]
		public string mcs_message { get; set; }
		[DataMember]
		public string mcs_stackTrace { get; set; }
		[DataMember]
		public string mcs_suggestion { get; set; }
		[DataMember]
		public string mcs_type { get; set; }
	}
}
