using System;
using Microsoft.Xrm.Sdk;
using System.ComponentModel.Composition;
using System.Runtime.Serialization;
using VRM.Integration.Servicebus.Core;
using VRM.Integration.UDO.Messages;
/// <summary>
/// VIMT LOB Component for UDOInitiateCADD,InitiateCADD method, Response.
/// Code Generated by IMS on: 8/4/2015 10:18:39 AM
/// Version: 2015.06.02
/// </summary>
/// <param name=none></param>
/// <returns>none</returns>

namespace VRM.Integration.UDO.CADD.Messages
{
    [Export(typeof(IMessageBase))]
    [ExportMetadata("MessageType", MessageRegistry.UDOFindBankResponse)]
    [DataContract]
    public class UDOFindBankResponse : MessageBase
    {
        [DataMember]
        public string bankName { get; set; }
        [DataMember]
        public UDOFindBankExceptions UDOFindBankExceptions { get; set; }
    }
    
    [DataContract]
    public class UDOFindBankExceptions
    {
        [DataMember]
        public bool AppealExceptionOccured { get; set; }
        [DataMember]
        public string AppealExceptionMessage { get; set; }
        [DataMember]
        public bool ClaimantExceptionOccured { get; set; }
        [DataMember]
        public string ClaimantExceptionMessage { get; set; }
        [DataMember]
        public bool VeteranExceptionOccured { get; set; }
        [DataMember]
        public string VeteranExceptionMessage { get; set; }
        [DataMember]
        public bool PaymentExceptionOccured { get; set; }
        [DataMember]
        public string PaymentExceptionMessage { get; set; }
        [DataMember]
        public bool DdeftExceptionOccured { get; set; }
        [DataMember]
        public string DdeftExceptionMessage { get; set; }
    }
}