using System;
using System.ComponentModel.Composition;
using Microsoft.Xrm.Sdk;
using System.Runtime.Serialization;
using VRM.Integration.Servicebus.Core;
using VRM.Integration.UDO.Messages;

/// <summary>
/// VIMT LOB Component for UDOInitiateCADD,InitiateCADD method, Request.
/// Code Generated by IMS on: 8/4/2015 10:18:38 AM
/// Version: 2015.06.02
/// </summary>
/// <param name=none></param>
/// <returns>none</returns>
namespace VRM.Integration.UDO.CADD.Messages
{
    [Export(typeof(IMessageBase))]
    [ExportMetadata("MessageType", MessageRegistry.UDOupdateCADDAddressRequest)]
    [DataContract]
    public class UDOupdateCADDAddressRequest : MessageBase
    {
        [DataMember]
        public string OrganizationName { get; set; }
        [DataMember]
        public Guid UserId { get; set; }
        [DataMember]
        public Guid RelatedParentId { get; set; }
        [DataMember]
        public string RelatedParentEntityName { get; set; }
        [DataMember]
        public string RelatedParentFieldName { get; set; }
        [DataMember]
        public bool LogTiming { get; set; }
        [DataMember]
        public bool LogSoap { get; set; }
        [DataMember]
        public bool Debug { get; set; }
        [DataMember]
        public HeaderInfo LegacyServiceHeaderInfo { get; set; }
        [DataMember]
        public Guid va_bankaccountId { get; set; }
        [DataMember]
        public string fileNumber { get; set; }
        [DataMember]
        public Int64 ptcpntId { get; set; }
        [DataMember]
        public Int64 ParticipantId { get; set; }
        [DataMember]
        public string PayeeCode { get; set; }
        [DataMember]
        public string RoutingTransitNumber {get;set;}
        [DataMember]
        public UDOupdateCADDMailingAddress UDOupdateCADDMailingAddress { get; set; }
        [DataMember]
        public UDOupdateCADDPaymentAddress UDOupdateCADDPaymentAddress { get; set; }
        [DataMember]
        public UDOupdateCADDAppellantAddress UDOupdateCADDAppellantAddress { get; set; }
        [DataMember]
        public UDOupdateCADDInfo UDOupdateCADDInfo { get; set; }
    }
    [DataContract]
    public class UDOupdateCADDBank
    {
        [DataMember]
        public string BankName {get;set;}
        [DataMember]
        public string ParticipantFinclInstId {get;set;}
        [DataMember]
        public string TreasurySeqNumber {get;set;}
    }
    [DataContract]
    public class UDOupdateCADDMailingAddress
    {
        [DataMember]
        public string MailingAddressLine1 { get; set; }
        [DataMember]
        public string MailingAddressLine2 { get; set; }
        [DataMember]
        public string MailingAddressLine3 { get; set; }
        [DataMember]
        public string MailingAddressCity { get; set; }
        [DataMember]
        public string MailingAddressState { get; set; }
        [DataMember]
        public string MailingAddressCountry { get; set; }
        [DataMember]
        public string MailingAddressZipCode { get; set; }
        [DataMember]
        public DateTime MailingAddressEffectiveDate { get; set; }
        [DataMember]
        public string ForeignMailCode { get; set; }
    }
    [DataContract]
    public class UDOupdateCADDPaymentAddress
    {
        [DataMember]
        public string PaymentAddressLine1 { get; set; }
        [DataMember]
        public string PaymentAddressLine2 { get; set; }
        [DataMember]
        public string PaymentAddressLine3 { get; set; }
        [DataMember]
        public string PaymentAddressCity { get; set; }
        [DataMember]
        public string PaymentAddressState { get; set; }
        [DataMember]
        public string PaymentAddressZipCode { get; set; }
        [DataMember]
        public string PaymentAddressCountry { get; set; }
        [DataMember]
        public DateTime PaymentAddressEffectiveDate { get; set; }
        [DataMember]
        public string PaymentForeignZipCode { get; set; }
        [DataMember]
        public string PaymentPostalTypeCode { get; set; }
        [DataMember]
        public string PaymentPoTypeCode { get; set; }
    }
    [DataContract]
    public class UDOupdateCADDAppellantAddress
    {
        [DataMember]
        public string AppellantAddressLine1 { get; set; }
        [DataMember]
        public string AppellantAddressLine2 { get; set; }
        [DataMember]
        public string AppellantAddressCity { get; set; }
        [DataMember]
        public string AppellantAddressState { get; set; }
        [DataMember]
        public string AppellantAddressZipCode { get; set; }
        [DataMember]
        public string AppellantAddressCountry { get; set; }
        [DataMember]
        public string AppellantAddressPhone1 { get; set; }
        [DataMember]
        public string AppellantAddressPhone2 { get; set; }
        [DataMember]
        public string LastUpdatedDate { get; set; }
        [DataMember]
        public string AddressKey { get; set; }

    }

    [DataContract]
    public class UDOupdateCADDInfo
    {
        [DataMember]
        public string Phone1 { get; set; }
        [DataMember]
        public string Phone1Type { get; set; }
        [DataMember]
        public string Phone2 { get; set; }
        [DataMember]
        public string Phone2Type { get; set; }
        [DataMember]
        public string PayeeLastName { get; set; }
        [DataMember]
        public string PayeeMiddleName { get; set; }
        [DataMember]
        public string PayeeFirstName { get; set; }
        [DataMember]
        public string PayeeSuffix { get; set; }
        [DataMember]
        public string AreaNumber1 { get; set; }
        [DataMember]
        public string AreaNumber2 { get; set; }
        [DataMember]
        public string EFTRoutingNumber { get; set; }
        [DataMember]
        public string EFTAccountNumber { get; set; }
        [DataMember]
        public string EFTAccountType { get; set; }
        [DataMember]
        public string ProvinceName { get; set; }
        [DataMember]
        public string TerritoryName { get; set; }
        [DataMember]
        public string MilitaryPostalCode { get; set; }
        [DataMember]
        public string MilitaryPostOfficeTypeCode { get; set; }
        [DataMember]
        public string ptcpntIdPayee { get; set; }
        [DataMember]
        public string ptcpntIdVet { get; set; }
        [DataMember]
        public string ptcpntIdBene { get; set; }
        [DataMember]
        public string ptcpntIdRecip { get; set; }
        [DataMember]
        public string awardTypeCd { get; set; }
        [DataMember]
        public string emailAddress { get; set; }
        [DataMember]
        public string addressType { get; set; }
    }
}