using System;
using Microsoft.Xrm.Sdk;
using System.ComponentModel.Composition;
using System.Runtime.Serialization;
using VRM.Integration.Servicebus.Core;
using VRM.Integration.UDO.Common.Messages;
using VRM.Integration.UDO.Messages;
/// <summary>
/// VIMT LOB Component for UDORetrieveNotes, RetrieveNotes method, Response.
/// Code Generated by IMS on: 6/27/2015 2:01:47 PM
/// Version: 2015.06.02
/// </summary>
/// <param name=none></param>
/// <returns>none</returns>

namespace VRM.Integration.UDO.Notes.Messages
{
    [Export(typeof(IMessageBase))]
    [ExportMetadata("MessageType", MessageRegistry.UDORetrieveNotesResponse)]
    [DataContract]
    public class UDORetrieveNotesResponse : UDOResponseBase
    {
        [DataMember]
        public int RecordCount { get; set; }
    }
}