using System;
using Microsoft.Xrm.Sdk;
using System.ComponentModel.Composition;
using System.Runtime.Serialization;
using VRM.Integration.Servicebus.Core;
/// <summary>
/// VIMT LOB Component for UDOUDOcreateDisabilityDetails,UDOcreateDisabilityDetails method, Response.
/// Code Generated by IMS on: 6/11/2015 2:06:37 PM
/// Version: 2015.06.02
/// </summary>
/// <param name=none></param>
/// <returns>none</returns>

namespace VRM.Integration.UDO.Ratings.Messages
{
    [Export(typeof(IMessageBase))]
    [ExportMetadata("MessageType", MessageRegistry.UDOcreateDisabilityDetailsResponse)]
    [DataContract]
    public class UDOcreateDisabilityDetailsResponse : MessageBase
    {
        [DataMember]
        public bool ExceptionOccured { get; set; }
        [DataMember]
        public string ExceptionMessage { get; set; }
        [DataMember]
        public UDOUDOcreateDisabilityDetailsMultipleResponse[] UDOUDOcreateDisabilityDetailsInfo { get; set; }
    }
    [DataContract]
    public class UDOUDOcreateDisabilityDetailsMultipleResponse
    {
        [DataMember]
        public Guid newUDOUDOcreateDisabilityDetailsId { get; set; }
    }
}
