using System;
using Microsoft.Xrm.Sdk;
using System.ComponentModel.Composition;
using System.Runtime.Serialization;
using VRM.Integration.Servicebus.Core;
/// <summary>
/// VIMT LOB Component for UDOUDOcreateFamilyMemberRatings,UDOcreateFamilyMemberRatings method, Response.
/// Code Generated by IMS on: 6/12/2015 1:55:52 PM
/// Version: 2015.06.02
/// </summary>
/// <param name=none></param>
/// <returns>none</returns>

namespace VRM.Integration.UDO.Ratings.Messages
{
    [Export(typeof(IMessageBase))]
    [ExportMetadata("MessageType", MessageRegistry.UDOcreateFamilyMemberRatingsResponse)]
    [DataContract]
    public class UDOcreateFamilyMemberRatingsResponse : MessageBase
    {
        [DataMember]
        public bool ExceptionOccured { get; set; }
        [DataMember]
        public string ExceptionMessage { get; set; }
        [DataMember]
        public UDOUDOcreateFamilyMemberRatingsMultipleResponse[] UDOUDOcreateFamilyMemberRatingsInfo { get; set; }
    }
    [DataContract]
    public class UDOUDOcreateFamilyMemberRatingsMultipleResponse
    {
        [DataMember]
        public Guid newUDOUDOcreateFamilyMemberRatingsId { get; set; }
    }
}
