using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.PersonService.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.PersonService,findPersonBySSN method, Response.
	/// Code Generated by IMS on: 12/27/2018 4:00:35 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISFPSSNfindPersonBySSNResponse : VEISEcResponseBase
	{
		[DataMember]
		public VEISFPSSNpersonDTO VEISFPSSNpersonDTOInfo { get; set; }
	}
	[DataContract]
	public class VEISFPSSNpersonDTO
	{
		[DataMember]
		public string mcs_birthCityNm { get; set; }
		[DataMember]
		public string mcs_birthStateCd { get; set; }
		[DataMember]
		public DateTime mcs_brthdyDt { get; set; }
		[DataMember]
		public bool mcs_brthdyDtSpecified { get; set; }
		[DataMember]
		public string mcs_cmptnyDecnTypeCd { get; set; }
		[DataMember]
		public string mcs_cmptnyDecnTypeNm { get; set; }
		[DataMember]
		public DateTime mcs_deathDt { get; set; }
		[DataMember]
		public bool mcs_deathDtSpecified { get; set; }
		[DataMember]
		public Int64 mcs_depNbr { get; set; }
		[DataMember]
		public bool mcs_depNbrSpecified { get; set; }
		[DataMember]
		public string mcs_emailAddr { get; set; }
		[DataMember]
		public string mcs_empInd { get; set; }
		[DataMember]
		public string mcs_entlmtTypeCd { get; set; }
		[DataMember]
		public string mcs_ethnicTypeCd { get; set; }
		[DataMember]
		public string mcs_fidDecnCategyTypeCd { get; set; }
		[DataMember]
		public string mcs_fidDecnCategyTypeNm { get; set; }
		[DataMember]
		public string mcs_fiduciaryInd { get; set; }
		[DataMember]
		public string mcs_fileNbr { get; set; }
		[DataMember]
		public string mcs_firstNm { get; set; }
		[DataMember]
		public Int64 mcs_firstNmKey { get; set; }
		[DataMember]
		public bool mcs_firstNmKeySpecified { get; set; }
		[DataMember]
		public Int64 mcs_frgnSvcNbr { get; set; }
		[DataMember]
		public bool mcs_frgnSvcNbrSpecified { get; set; }
		[DataMember]
		public string mcs_genderCd { get; set; }
		[DataMember]
		public DateTime mcs_jrnDt { get; set; }
		[DataMember]
		public bool mcs_jrnDtSpecified { get; set; }
		[DataMember]
		public string mcs_jrnLctnId { get; set; }
		[DataMember]
		public string mcs_jrnObjId { get; set; }
		[DataMember]
		public string mcs_jrnStatusTypeCd { get; set; }
		[DataMember]
		public string mcs_jrnUserId { get; set; }
		[DataMember]
		public string mcs_lastNm { get; set; }
		[DataMember]
		public Int64 mcs_lastNmKey { get; set; }
		[DataMember]
		public bool mcs_lastNmKeySpecified { get; set; }
		[DataMember]
		public string mcs_lgyEntlmtTypeCd { get; set; }
		[DataMember]
		public string mcs_middleNm { get; set; }
		[DataMember]
		public Int64 mcs_middleNmKey { get; set; }
		[DataMember]
		public bool mcs_middleNmKeySpecified { get; set; }
		[DataMember]
		public string mcs_mltyPersonInd { get; set; }
		[DataMember]
		public Int64 mcs_monthsPresntEmplyrNbr { get; set; }
		[DataMember]
		public bool mcs_monthsPresntEmplyrNbrSpecified { get; set; }
		[DataMember]
		public Int64 mcs_netWorthAmt { get; set; }
		[DataMember]
		public bool mcs_netWorthAmtSpecified { get; set; }
		[DataMember]
		public string mcs_noSsnReasonTypeCd { get; set; }
		[DataMember]
		public string mcs_ocptnTxt { get; set; }
		[DataMember]
		public string mcs_personDeathCauseTypeNm { get; set; }
		[DataMember]
		public string mcs_personTypeNm { get; set; }
		[DataMember]
		public string mcs_potntlDngrsInd { get; set; }
		[DataMember]
		public Int64 mcs_ptcpntId { get; set; }
		[DataMember]
		public bool mcs_ptcpntIdSpecified { get; set; }
		[DataMember]
		public string mcs_ptcpntRlnshpTypeNm { get; set; }
		[DataMember]
		public string mcs_raceTypeNm { get; set; }
		[DataMember]
		public bool mcs_sbstncAmtSpecified { get; set; }
		[DataMember]
		public string mcs_serousEmplmtHndcapInd { get; set; }
		[DataMember]
		public string mcs_slttnTypeNm { get; set; }
		[DataMember]
		public string mcs_spinaBifidaInd { get; set; }
		[DataMember]
		public string mcs_ssnNbr { get; set; }
		[DataMember]
		public string mcs_ssnVrfctnStatusTypeCd { get; set; }
		[DataMember]
		public string mcs_stationOfJurisdiction { get; set; }
		[DataMember]
		public string mcs_suffixNm { get; set; }
		[DataMember]
		public Int64 mcs_suffixNmKey { get; set; }
		[DataMember]
		public bool mcs_suffixNmKeySpecified { get; set; }
		[DataMember]
		public string mcs_taxAbtmntCd { get; set; }
		[DataMember]
		public string mcs_termnlDigitNbr { get; set; }
		[DataMember]
		public string mcs_titleTxt { get; set; }
		[DataMember]
		public string mcs_vetInd { get; set; }
		[DataMember]
		public string mcs_vetTypeNm { get; set; }
		[DataMember]
		public Int64 mcs_yearsPresntEmplyrNbr { get; set; }
		[DataMember]
		public bool mcs_yearsPresntEmplyrNbrSpecified { get; set; }
		[DataMember]
		public VEISFPSSNptcpntPhoneDTOMultipleResponse[] VEISFPSSNptcpntPhoneDTOInfo { get; set; }
		[DataMember]
		public VEISFPSSNsbstncAmt VEISFPSSNsbstncAmtInfo { get; set; }
		[DataMember]
		public VEISFPSSNsntvtyLevelDTO VEISFPSSNsntvtyLevelDTOInfo { get; set; }
	}
	[DataContract]
	public class VEISFPSSNptcpntPhoneDTOMultipleResponse
	{
		[DataMember]
		public Int32 mcs_areaNbr { get; set; }
		[DataMember]
		public bool mcs_areaNbrSpecified { get; set; }
		[DataMember]
		public Int32 mcs_cntryNbr { get; set; }
		[DataMember]
		public bool mcs_cntryNbrSpecified { get; set; }
		[DataMember]
		public Int32 mcs_extnsnNbr { get; set; }
		[DataMember]
		public bool mcs_extnsnNbrSpecified { get; set; }
		[DataMember]
		public string mcs_frgnPhoneRfrncTxt { get; set; }
		[DataMember]
		public Int64 mcs_phoneNbr { get; set; }
		[DataMember]
		public VEISFPSSNcompId VEISFPSSNcompIdInfo { get; set; }
	}
	[DataContract]
	public class VEISFPSSNcompId
	{
		[DataMember]
		public DateTime mcs_efctvDt { get; set; }
		[DataMember]
		public bool mcs_efctvDtSpecified { get; set; }
		[DataMember]
		public string mcs_phoneTypeNm { get; set; }
		[DataMember]
		public Int64 mcs_ptcpntId { get; set; }
		[DataMember]
		public bool mcs_ptcpntIdSpecified { get; set; }
	}
	[DataContract]
	public class VEISFPSSNsbstncAmt
	{
	}
	[DataContract]
	public class VEISFPSSNsntvtyLevelDTO
	{
		[DataMember]
		public string mcs_bdnStnNbr { get; set; }
		[DataMember]
		public string mcs_birlsFolderLctnTxt { get; set; }
		[DataMember]
		public string mcs_cd { get; set; }
		[DataMember]
		public string mcs_dgnstcSuprsnInd { get; set; }
		[DataMember]
		public string mcs_fcltyTypeCd { get; set; }
		[DataMember]
		public DateTime mcs_jrnDt { get; set; }
		[DataMember]
		public bool mcs_jrnDtSpecified { get; set; }
		[DataMember]
		public string mcs_jrnLctnId { get; set; }
		[DataMember]
		public string mcs_jrnObjId { get; set; }
		[DataMember]
		public string mcs_jrnStatusTypeCd { get; set; }
		[DataMember]
		public string mcs_jrnUserId { get; set; }
		[DataMember]
		public Int64 mcs_mtgeLoanId { get; set; }
		[DataMember]
		public bool mcs_mtgeLoanIdSpecified { get; set; }
		[DataMember]
		public Int64 mcs_ptcpntId { get; set; }
		[DataMember]
		public bool mcs_ptcpntIdSpecified { get; set; }
		[DataMember]
		public DateTime mcs_reviewDt { get; set; }
		[DataMember]
		public bool mcs_reviewDtSpecified { get; set; }
		[DataMember]
		public string mcs_rmksTxt { get; set; }
		[DataMember]
		public string mcs_scrtyLevelTypeCd { get; set; }
		[DataMember]
		public Int64 mcs_sntvtyLevelId { get; set; }
		[DataMember]
		public bool mcs_sntvtyLevelIdSpecified { get; set; }
		[DataMember]
		public string mcs_sntvtyReasonTypeNm { get; set; }
	}
}
