using System; 
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.DocGenService.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.DocGenService,ConvertWordToPdf method, Response.
	/// Code Generated by IMS on: 1/11/2019 10:27:23 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISConvertWordToPdfResponse : VEISEcResponseBase
	{
		[DataMember]
		public VEISPdfServiceResponse VEISPdfServiceResponseInfo { get; set; }
	}
	[DataContract]
	public class VEISPdfServiceResponse
	{
		[DataMember]
		public System.Runtime.Serialization.ExtensionDataObject mcs_ExtensionData { get; set; }
		[DataMember]
		public string mcs_Message { get; set; }
		[DataMember]
		public Byte[] mcs_OutputFileBytes { get; set; }
		[DataMember]
		public bool mcs_Succeeded { get; set; }
	}
}
