using System;
using System.ComponentModel.Composition;
using System.Runtime.Serialization;
using UDO.LOB.Core;
using UDO.LOB.Extensions;
using VEIS.Core.Messages;

//using Microsoft.Xrm.Sdk;
//using VRM.Integration.Servicebus.Core

/// <summary>
/// VIMT LOB Component for UDOUDOcreateSMCParagraphRatings,UDOcreateSMCParagraphRatings method, Response.
/// Code Generated by IMS on: 6/12/2015 3:32:20 PM
/// Version: 2015.06.02
/// </summary>
/// <param name=none></param>
/// <returns>none</returns>

namespace UDO.LOB.Ratings.Messages
{
    //[Export(typeof(IMessageBase))]
    //[ExportMetadata("MessageType", MessageRegistry.UDOcreateSMCParagraphRatingsResponse)]
    [DataContract]
    public class UDOcreateSMCParagraphRatingsResponse : MessageBase
    {
        [DataMember]
        public bool ExceptionOccurred { get; set; }
        [DataMember]
        public string ExceptionMessage { get; set; }
        [DataMember]
        public UDOUDOcreateSMCParagraphRatingsMultipleResponse[] UDOUDOcreateSMCParagraphRatingsInfo { get; set; }
    }
    [DataContract]
    public class UDOUDOcreateSMCParagraphRatingsMultipleResponse
    {
        [DataMember]
        public Guid newUDOUDOcreateSMCParagraphRatingsId { get; set; }
    }
}
