using System;
using System.Runtime.Serialization;
using UDO.LOB.Core;

//using System.ComponentModel.Composition;
//using UDO.LOB.Extensions;
//using VEIS.Core.Messages;

//using Microsoft.Xrm.Sdk;
//using VRM.Integration.Servicebus.Core;
//using VRM.Integration.UDO.Common.Interfaces;
//using VRM.Integration.UDO.Common.Messages;

/// <summary>
/// VIMT LOB Component for UDOUDOcreateSMCRatings,UDOcreateSMCRatings method, Response.
/// Code Generated by IMS on: 6/12/2015 3:18:51 PM
/// Version: 2015.06.02
/// </summary>
/// <param name=none></param>
/// <returns>none</returns>

namespace UDO.LOB.Ratings.Messages
{
    //[Export(typeof(IMessageBase))]
    //[ExportMetadata("MessageType", MessageRegistry.UDOfindRatingsResponse)]
    [DataContract]
    public class UDOfindRatingsResponse : MessageBase
    {
        [DataMember]
        public bool ExceptionOccurred { get; set; }
        [DataMember]
        public string ExceptionMessage { get; set; }
        [DataMember]
        public UDOcreateSMCRatingsMultipleResponse[] UDOcreateSMCRatingsInfo { get; set; }
        [DataMember]
        public UDOcreateSMCParagraphRatingsMultipleResponse[] UDOcreateSMCParagraphRatingsInfo { get; set; }
        [DataMember]
        public UDOcreateOtherRatingsMultipleResponse[] UDOcreateOtherRatingsInfo { get; set; }
        [DataMember]
        public UDOcreateFamilyMemberRatingsMultipleResponse[] UDOcreateFamilyMemberRatingsInfo { get; set; }
        [DataMember]
        public UDOcreateDisabilityRatingsMultipleResponse[] UDOcreateDisabilityRatingsInfo { get; set; }
        [DataMember]
        public UDOcreateDisabilityDetailsMultipleResponse[] UDOcreateDisabilityDetailsInfo { get; set; }
        [DataMember]
        public UDOcreateDeathRatingsMultipleResponse[] UDOcreateDeathRatingsInfo { get; set; }


    }
    [DataContract]
    public class UDOcreateSMCRatingsMultipleResponse
    {
        [DataMember]
        public Guid newUDOUDOcreateSMCRatingsId { get; set; }
    }
    [DataContract]
    public class UDOcreateSMCParagraphRatingsMultipleResponse
    {
        [DataMember]
        public Guid newUDOUDOcreateSMCParagraphRatingsId { get; set; }
    }
    [DataContract]
    public class UDOcreateDisabilityRatingsMultipleResponse
    {
        [DataMember]
        public Guid newUDOUDOcreateDisabilityRatingsId { get; set; }
    }
    [DataContract]
    public class UDOcreateDisabilityDetailsMultipleResponse
    {
        [DataMember]
        public Guid newUDOUDOcreateDisabilityDetailsId { get; set; }
    }
    [DataContract]
    public class UDOcreateOtherRatingsMultipleResponse
    {
        [DataMember]
        public Guid newUDOUDOcreateOtherRatingsId { get; set; }
    }
    [DataContract]
    public class UDOcreateFamilyMemberRatingsMultipleResponse
    {
        [DataMember]
        public Guid newUDOUDOcreateFamilyMemberRatingsId { get; set; }
    }
    [DataContract]
    public class UDOcreateDeathRatingsMultipleResponse
    {
        [DataMember]
        public Guid newUDOUDOcreateDeathRatingsId { get; set; }
    }
}
