using System;
using System.ComponentModel.Composition;
using System.Runtime.Serialization;
using UDO.LOB.Core;

//using VRM.Integration.Servicebus.Core;
//using VRM.Integration.UDO.Messages;

/// <summary>
/// VIMT LOB Component for UDOcreateUDOLegacyPaymentData,createUDOLegacyPaymentData method, Response.
/// Code Generated by IMS on: 7/13/2015 6:24:18 PM
/// Version: 2015.06.02
/// </summary>
/// <param name=none></param>
/// <returns>none</returns>

namespace UDO.LOB.IntentToFile.Messages
{
    //[Export(typeof(IMessageBase))]
    // [ExportMetadata("MessageType", MessageRegistry.UDOvalidateAddressResponse)]
    [DataContract]
    public class UDOvalidateAddressResponse : MessageBase
    {
        [DataMember]
        public MultipleAddressResponse[] Addresses { get; set; }
        [DataMember]
        public bool ExceptionOccurred { get; set; }
        [DataMember]
        public string ExceptionMessage { get; set; }
    }
    [DataContract]
    public class MultipleAddressResponse
    {
        [DataMember]
        public string abbreviatedAliasResult { get; set; }
        [DataMember]
        public string additionalInputData { get; set; }
        [DataMember]
        public string addressBlock1 { get; set; }
        [DataMember]
        public string addressBlock2 { get; set; }
        [DataMember]
        public string addressBlock3 { get; set; }
        [DataMember]
        public string addressBlock4 { get; set; }
        [DataMember]
        public string addressBlock5 { get; set; }
        [DataMember]
        public string addressBlock6 { get; set; }
        [DataMember]
        public string addressBlock7 { get; set; }
        [DataMember]
        public string addressBlock8 { get; set; }
        [DataMember]
        public string addressBlock9 { get; set; }
        [DataMember]
        public string addressFormat { get; set; }
        [DataMember]
        public string addressLine1 { get; set; }
        [DataMember]
        public string addressLine2 { get; set; }
        [DataMember]
        public string addressLine3 { get; set; }
        [DataMember]
        public string addressLine4 { get; set; }
        [DataMember]
        public string apartmentLabel { get; set; }
        [DataMember]
        public string apartmentLabel2 { get; set; }
        [DataMember]
        public string apartmentLabel2Result { get; set; }
        [DataMember]
        public string apartmentLabelInput { get; set; }
        [DataMember]
        public string apartmentLabelResult { get; set; }
        [DataMember]
        public string apartmentNumber { get; set; }
        [DataMember]
        public string apartmentNumber2 { get; set; }
        [DataMember]
        public string apartmentNumber2Result { get; set; }
        [DataMember]
        public string apartmentNumberInput { get; set; }
        [DataMember]
        public string apartmentNumberResult { get; set; }
        [DataMember]
        public string CMRA { get; set; }
        [DataMember]
        public string canadianDeliveryInstallationAreaName { get; set; }
        [DataMember]
        public string canadianDeliveryInstallationAreaNameInput { get; set; }
        [DataMember]
        public string canadianDeliveryInstallationQualifierName { get; set; }
        [DataMember]
        public string canadianDeliveryInstallationQualifierNameInput { get; set; }
        [DataMember]
        public string canadianDeliveryInstallationType { get; set; }
        [DataMember]
        public string canadianDeliveryInstallationTypeInput { get; set; }
        [DataMember]
        public string canadianSERPCode { get; set; }
        [DataMember]
        public string city { get; set; }
        [DataMember]
        public string cityInput { get; set; }
        [DataMember]
        public string cityResult { get; set; }
        [DataMember]
        public string confidence { get; set; }
        [DataMember]
        public string couldNotValidate { get; set; }
        [DataMember]
        public string country { get; set; }
        [DataMember]
        public string countryInput { get; set; }
        [DataMember]
        public string countryLevel { get; set; }
        [DataMember]
        public string countryResult { get; set; }
        [DataMember]
        public string DPV { get; set; }
        [DataMember]
        public string DPVFootnote { get; set; }
        [DataMember]
        public string DPVNoStat { get; set; }
        [DataMember]
        public string DPVVacant { get; set; }
        [DataMember]
        public string firmName { get; set; }
        [DataMember]
        public string firmNameInput { get; set; }
        [DataMember]
        public string firmNameResult { get; set; }
        [DataMember]
        public string houseNumber { get; set; }
        [DataMember]
        public string houseNumberInput { get; set; }
        [DataMember]
        public string houseNumberResult { get; set; }
        [DataMember]
        public string leadingDirectional { get; set; }
        [DataMember]
        public string leadingDirectionalInput { get; set; }
        [DataMember]
        public string leadingDirectionalResult { get; set; }
        [DataMember]
        public string matchScore { get; set; }
        [DataMember]
        public string multimatchCount { get; set; }
        [DataMember]
        public string multipleMatches { get; set; }
        [DataMember]
        public string POBox { get; set; }
        [DataMember]
        public string POBoxInput { get; set; }
        [DataMember]
        public string POBoxResult { get; set; }
        [DataMember]
        public string postalBarCode { get; set; }
        [DataMember]
        public string postalCode { get; set; }
        [DataMember]
        public string postalCodeAddOn { get; set; }
        [DataMember]
        public string postalCodeBase { get; set; }
        [DataMember]
        public string postalCodeInput { get; set; }
        [DataMember]
        public string postalCodeResult { get; set; }
        [DataMember]
        public string postalCodeSource { get; set; }
        [DataMember]
        public string postalCodeType { get; set; }
        [DataMember]
        public string preferredAliasResult { get; set; }
        [DataMember]
        public string privateMailbox { get; set; }
        [DataMember]
        public string privateMailboxInput { get; set; }
        [DataMember]
        public string privateMailboxType { get; set; }
        [DataMember]
        public string privateMailboxTypeInput { get; set; }
        [DataMember]
        public string processedBy { get; set; }
        [DataMember]
        public string RDI { get; set; }
        [DataMember]
        public string RRHC { get; set; }
        [DataMember]
        public string RRHCInput { get; set; }
        [DataMember]
        public string RRHCResult { get; set; }
        [DataMember]
        public string RRHCType { get; set; }
        [DataMember]
        public string recordType { get; set; }
        [DataMember]
        public string recordTypeDefault { get; set; }
        [DataMember]
        public string stateProvince { get; set; }
        [DataMember]
        public string stateProvinceInput { get; set; }
        [DataMember]
        public string stateProvinceResult { get; set; }
        [DataMember]
        public string status { get; set; }
        [DataMember]
        public string statusCode { get; set; }
        [DataMember]
        public string statusDescription { get; set; }
        [DataMember]
        public string streetName { get; set; }
        [DataMember]
        public string streetNameAbbreviatedAliasResult { get; set; }
        [DataMember]
        public string streetNameAliasType { get; set; }
        [DataMember]
        public string streetNameInput { get; set; }
        [DataMember]
        public string streetNamePreferredAliasResult { get; set; }
        [DataMember]
        public string streetNameResult { get; set; }
        [DataMember]
        public string streetSuffix { get; set; }
        [DataMember]
        public string streetSuffixInput { get; set; }
        [DataMember]
        public string streetSuffixResult { get; set; }
        [DataMember]
        public string suiteLinkFidelity { get; set; }
        [DataMember]
        public string suiteLinkMatchCode { get; set; }
        [DataMember]
        public string suiteLinkReturnCode { get; set; }
        [DataMember]
        public string trailingDirectional { get; set; }
        [DataMember]
        public string trailingDirectionalInput { get; set; }
        [DataMember]
        public string trailingDirectionalResult { get; set; }
        [DataMember]
        public string USAltAddr { get; set; }
        [DataMember]
        public string USBCCheckDigit { get; set; }
        [DataMember]
        public string USCarrierRouteCode { get; set; }
        [DataMember]
        public string USCongressionalDistrict { get; set; }
        [DataMember]
        public string USCountyName { get; set; }
        [DataMember]
        public string USFIPSCountyNumber { get; set; }
        [DataMember]
        public string USFinanceNumber { get; set; }
        [DataMember]
        public string USLACS { get; set; }
        [DataMember]
        public string USLACSReturnCode { get; set; }
        [DataMember]
        public string USLOTCode { get; set; }
        [DataMember]
        public string USLOTHex { get; set; }
        [DataMember]
        public string USLOTSequence { get; set; }
        [DataMember]
        public string USLastLineNumber { get; set; }
        [DataMember]
        public string USUrbanName { get; set; }
        [DataMember]
        public string USUrbanNameInput { get; set; }
        [DataMember]
        public string USUrbanNameResult { get; set; }
        [DataMember]
        public string usImDestinationDATF { get; set; }
        [DataMember]
        public string usImDestinationRaw { get; set; }
        [DataMember]
        public string usImGenericDATF { get; set; }
        [DataMember]
        public string usImGenericRaw { get; set; }
        [DataMember]
        public string usImOriginDATF { get; set; }
        [DataMember]
        public string usImOriginRaw { get; set; }
        [DataMember]
        public string veriMoveDataBlock { get; set; }
    }
}