using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.ProviderAdpaterService.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.ProviderAdpaterService,findProviderById method, Response.
	/// Code Generated by IMS on: 1/11/2019 10:49:00 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISfprobidfindProviderByIdResponse : VEISEcResponseBase
	{
		[DataMember]
		public VEISfprobidFindProviderByIdResponseMessage_v1 VEISfprobidFindProviderByIdResponseMessage_v1Info { get; set; }
	}
	[DataContract]
	public class VEISfprobidFindProviderByIdResponseMessage_v1
	{
		[DataMember]
		public VEISfprobidprovidersMultipleResponse[] VEISfprobidprovidersInfo { get; set; }
		[DataMember]
		public VEISfprobidresponseStats VEISfprobidresponseStatsInfo { get; set; }
		[DataMember]
		public VEISfprobidfault VEISfprobidfaultInfo { get; set; }
	}
	[DataContract]
	public class VEISfprobidprovidersMultipleResponse
	{
		[DataMember]
		public string mcs_vendorName { get; set; }
		[DataMember]
		public string mcs_npi { get; set; }
		[DataMember]
		public string mcs_vendorPOAExempt { get; set; }
		[DataMember]
		public String[] mcs_drgNumbers { get; set; }
		[DataMember]
		public string mcs_vcom { get; set; }
		[DataMember]
		public string mcs_vendorAddressCode { get; set; }
		[DataMember]
		public string mcs_internalModifier { get; set; }
		[DataMember]
		public string mcs_specialty { get; set; }
		[DataMember]
		public string mcs_billPhone { get; set; }
		[DataMember]
		public string mcs_billFaxNumber { get; set; }
		[DataMember]
		public string mcs_contactPhone { get; set; }
		[DataMember]
		public string mcs_fmsNumber { get; set; }
		[DataMember]
		public string mcs_deaNumberContactPhone { get; set; }
		[DataMember]
		public string mcs_eftBankNumber { get; set; }
		[DataMember]
		public string mcs_eftBankFlag { get; set; }
		[DataMember]
		public string mcs_eftAccountNumber { get; set; }
		[DataMember]
		public string mcs_eftBankName { get; set; }
		[DataMember]
		public string mcs_eftBankCity { get; set; }
		[DataMember]
		public string mcs_eftBankState { get; set; }
		[DataMember]
		public string mcs_eftBankZip { get; set; }
		[DataMember]
		public string mcs_eftCorrBankNumber { get; set; }
		[DataMember]
		public string mcs_eftCorrBankName { get; set; }
		[DataMember]
		public VEISfprobidproviderIdentifier VEISfprobidproviderIdentifierInfo { get; set; }
		[DataMember]
		public VEISfprobidproviderTypeMultipleResponse[] VEISfprobidproviderTypeInfo { get; set; }
		[DataMember]
		public VEISfprobidstatusMultipleResponse[] VEISfprobidstatusInfo { get; set; }
		[DataMember]
		public VEISfprobidaddressesMultipleResponse[] VEISfprobidaddressesInfo { get; set; }
		[DataMember]
		public VEISfprobidaustinVerifiedMultipleResponse[] VEISfprobidaustinVerifiedInfo { get; set; }
		[DataMember]
		public VEISfprobidcmacMultipleResponse[] VEISfprobidcmacInfo { get; set; }
		[DataMember]
		public VEISfprobidbillName VEISfprobidbillNameInfo { get; set; }
		[DataMember]
		public VEISfprobidsanctioningMultipleResponse[] VEISfprobidsanctioningInfo { get; set; }
		[DataMember]
		public VEISfprobideicSSNMultipleResponse[] VEISfprobideicSSNInfo { get; set; }
	}
	[DataContract]
	public class VEISfprobidproviderIdentifier
	{
		[DataMember]
		public string mcs_ien { get; set; }
		[DataMember]
		public string mcs_ein { get; set; }
	}
	[DataContract]
	public class VEISfprobidproviderTypeMultipleResponse
	{
		[DataMember]
		public string mcs_code { get; set; }
		[DataMember]
		public string mcs_description { get; set; }
	}
	[DataContract]
	public class VEISfprobidstatusMultipleResponse
	{
		[DataMember]
		public string mcs_code { get; set; }
		[DataMember]
		public string mcs_description { get; set; }
	}
	[DataContract]
	public class VEISfprobidaddressesMultipleResponse
	{
		[DataMember]
		public string mcs_name { get; set; }
		[DataMember]
		public VEISfprobidaddress VEISfprobidaddressInfo { get; set; }
	}
	[DataContract]
	public class VEISfprobidaddress
	{
		[DataMember]
		public bool mcs_typeSpecified { get; set; }
		[DataMember]
		public string mcs_addressLine1 { get; set; }
		[DataMember]
		public string mcs_addressLine2 { get; set; }
		[DataMember]
		public string mcs_addressCityName { get; set; }
		[DataMember]
		public string mcs_addressUSStateCode { get; set; }
		[DataMember]
		public string mcs_addressZip5PostalCode { get; set; }
		[DataMember]
		public string mcs_country { get; set; }
		[DataMember]
		public bool mcs_foreignAddressFlag { get; set; }
		[DataMember]
		public bool mcs_foreignAddressFlagSpecified { get; set; }
		[DataMember]
		public VEISfprobidtype VEISfprobidtypeInfo { get; set; }
	}
	[DataContract]
	public enum VEISfprobidtype
	{
		SponsorRemitto,
		SponsorCorrespondence,
		BeneficiaryRemitto,
		BeneficiaryCorrespondence,
		ProviderRemitto,
		ProviderBilling,
		ProviderProvider,
		ContactContact,
	}
	[DataContract]
	public class VEISfprobidaustinVerifiedMultipleResponse
	{
		[DataMember]
		public string mcs_code { get; set; }
		[DataMember]
		public string mcs_description { get; set; }
	}
	[DataContract]
	public class VEISfprobidcmacMultipleResponse
	{
		[DataMember]
		public string mcs_code { get; set; }
		[DataMember]
		public string mcs_description { get; set; }
	}
	[DataContract]
	public class VEISfprobidbillName
	{
		[DataMember]
		public string mcs_prefix { get; set; }
		[DataMember]
		public string mcs_firstName { get; set; }
		[DataMember]
		public string mcs_middleName { get; set; }
		[DataMember]
		public string mcs_lastName { get; set; }
		[DataMember]
		public string mcs_suffix { get; set; }
	}
	[DataContract]
	public class VEISfprobidsanctioningMultipleResponse
	{
		[DataMember]
		public DateTime mcs_beginDate { get; set; }
		[DataMember]
		public bool mcs_beginDateSpecified { get; set; }
		[DataMember]
		public DateTime mcs_endDate { get; set; }
		[DataMember]
		public bool mcs_endDateSpecified { get; set; }
		[DataMember]
		public string mcs_authority { get; set; }
	}
	[DataContract]
	public class VEISfprobideicSSNMultipleResponse
	{
		[DataMember]
		public string mcs_code { get; set; }
		[DataMember]
		public string mcs_description { get; set; }
	}
	[DataContract]
	public class VEISfprobidresponseStats
	{
		[DataMember]
		public Int32 mcs_recordsReturned { get; set; }
		[DataMember]
		public bool mcs_recordsReturnedSpecified { get; set; }
		[DataMember]
		public bool mcs_moreChunkRecords { get; set; }
		[DataMember]
		public bool mcs_moreChunkRecordsSpecified { get; set; }
		[DataMember]
		public bool mcs_moreDateRecords { get; set; }
		[DataMember]
		public bool mcs_moreDateRecordsSpecified { get; set; }
		[DataMember]
		public Int32 mcs_totalRecords { get; set; }
		[DataMember]
		public bool mcs_totalRecordsSpecified { get; set; }
	}
	[DataContract]
	public class VEISfprobidfault
	{
		[DataMember]
		public bool mcs_essCodeSpecified { get; set; }
		[DataMember]
		public string mcs_essText { get; set; }
		[DataMember]
		public string mcs_code { get; set; }
		[DataMember]
		public string mcs_text { get; set; }
		[DataMember]
		public VEISfprobidessCode VEISfprobidessCodeInfo { get; set; }
		[DataMember]
		public VEISfprobidnestedFault VEISfprobidnestedFaultInfo { get; set; }
	}
	[DataContract]
	public enum VEISfprobidessCode
	{
		SUCCESS,
		ERROR,
		WARNING,
		REFUSED,
		ACCEPT,
		REJECT,
		FAIL,
	}
	[DataContract]
	public class VEISfprobidnestedFault
	{
		[DataMember]
		public bool mcs_essCodeSpecified { get; set; }
		[DataMember]
		public string mcs_essText { get; set; }
		[DataMember]
		public string mcs_code { get; set; }
		[DataMember]
		public string mcs_text { get; set; }
		[DataMember]
		public VEISfprobidessCode1 VEISfprobidessCode1Info { get; set; }
	}
	[DataContract]
	public enum VEISfprobidessCode1
	{
		SUCCESS,
		ERROR,
		WARNING,
		REFUSED,
		ACCEPT,
		REJECT,
		FAIL,
	}
}
