using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;
namespace VEIS.CpeForeignMedicalProgramAdapterServiceV3.CRMOL.Messages
{ 
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.CpeForeignMedicalProgramAdapterServiceV3.CRMOL,getFMPComments method, Response.
	/// Code Generated by IMS on: 6/1/2018 11:12:17 AM
	/// Version: 2018.05.09.05
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISgFMPCogetFMPCommentsResponse : VEISEcResponseBase
	{
		[DataMember]
		public VEISgFMPCoCPEForeignMedicalProgramAdapterv3getFMPCommentsResponse VEISgFMPCoCPEForeignMedicalProgramAdapterv3getFMPCommentsResponseInfo { get; set; }
		[DataMember]
		public bool ExceptionOccured { get; set; } 
	}
	[DataContract]
	public class VEISgFMPCoCPEForeignMedicalProgramAdapterv3getFMPCommentsResponse
	{
		[DataMember]
		public VEISgFMPCocode VEISgFMPCocodeInfo { get; set; }
		[DataMember]
		public VEISgFMPCocommentMultipleResponse[] VEISgFMPCocommentInfo { get; set; }
		[DataMember]
		public VEISgFMPCofault VEISgFMPCofaultInfo { get; set; }
	}
	[DataContract]
	public enum VEISgFMPCocode
	{
		SUCCESS,
		ERROR,
	}
	[DataContract]
	public class VEISgFMPCocommentMultipleResponse
	{
		[DataMember]
		public DateTime mcs_dateEntered { get; set; }
		[DataMember]
		public bool mcs_dateEnteredSpecified { get; set; }
		[DataMember]
		public string mcs_source { get; set; }
		[DataMember]
		public string mcs_comment { get; set; }
		[DataMember]
		public bool mcs_commentTypeSpecified { get; set; }
		[DataMember]
		public VEISgFMPCoenteredBy VEISgFMPCoenteredByInfo { get; set; }
		[DataMember]
		public VEISgFMPCocommentType VEISgFMPCocommentTypeInfo { get; set; }
	}
	[DataContract]
	public class VEISgFMPCoenteredBy
	{
		[DataMember]
		public string mcs_prefix { get; set; }
		[DataMember]
		public string mcs_firstName { get; set; }
		[DataMember]
		public string mcs_middleName { get; set; }
		[DataMember]
		public string mcs_lastName { get; set; }
		[DataMember]
		public string mcs_suffix { get; set; }
	}
	[DataContract]
	public enum VEISgFMPCocommentType
	{
		FMP,
		FMPAcceptance,
		Sponsor,
		Beneficiary,
		PDI,
		OHI,
		Claim,
	}
	[DataContract]
	public class VEISgFMPCofault
	{
		[DataMember]
		public bool mcs_essCodeSpecified { get; set; }
		[DataMember]
		public string mcs_essText { get; set; }
		[DataMember]
		public string mcs_code { get; set; }
		[DataMember]
		public string mcs_text { get; set; }
		[DataMember]
		public VEISgFMPCoessCode VEISgFMPCoessCodeInfo { get; set; }
		[DataMember]
		public VEISgFMPConestedFault VEISgFMPConestedFaultInfo { get; set; }
	}
	[DataContract]
	public enum VEISgFMPCoessCode
	{
		SUCCESS,
		ERROR,
		WARNING,
		REFUSED,
		ACCEPT,
		REJECT,
		FAIL,
	}
	[DataContract]
	public class VEISgFMPConestedFault
	{
		[DataMember]
		public bool mcs_essCodeSpecified { get; set; }
		[DataMember]
		public string mcs_essText { get; set; }
		[DataMember]
		public string mcs_code { get; set; }
		[DataMember]
		public string mcs_text { get; set; }
		[DataMember]
		public VEISgFMPCoessCode1 VEISgFMPCoessCode1Info { get; set; }
	}
	[DataContract]
	public enum VEISgFMPCoessCode1
	{
		SUCCESS,
		ERROR,
		WARNING,
		REFUSED,
		ACCEPT,
		REJECT,
		FAIL,
	}
}
