//using Microsoft.Xrm.Sdk;
using System;
using System.Collections.Generic;
using System.ComponentModel.Composition;
using System.Runtime.Serialization;
using UDO.LOB.Core;

//using VRM.Integration.Servicebus.Core;
//using VRM.Integration.UDO.Messages;

/// <summary>
/// VIMT LOB Component for UDOCreateFNOD,CreateFNOD method, Response.
/// Code Generated by IMS on: 10/12/2015 9:53:35 AM
/// Version: 2015.06.02
/// </summary>
/// <param name=none></param>
/// <returns>none</returns>

namespace UDO.LOB.FNOD.Messages
{
    [Export(typeof(IMessageBase))]
    //[ExportMetadata("MessageType", MessageRegistry.UDOInitiateFNODResponse)]
    [DataContract]
    public class UDOInitiateFNODResponse : MessageBase
    {
        [DataMember]
        public Guid newUDOInitiateFNODId { get; set; }
        [DataMember]
        public UDOInitiateFNODException UDOInitiateFNODExceptions { get; set; }
    }
   
    [DataContract]
    public class UDOInitiateFNODException
    {
        [DataMember]
        public bool ExceptionOccurred { get; set; }
        [DataMember]
        public string ExceptionMessage { get; set; }
    }
}
