using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.Messages.IntentToFileWebService
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.IntentToFileWebService,insertIntentToFile method, Response.
	/// Code Generated by IMS on: 1/7/2019 8:16:22 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISinsertInt2FileinsertIntentToFileResponse : VEISEcResponseBase
	{
		[DataMember]
		public VEISinsertInt2FileintentToFileDTO VEISinsertInt2FileintentToFileDTOInfo { get; set; }
	}
	[DataContract]
	public class VEISinsertInt2FileintentToFileDTO
	{
		[DataMember]
		public string mcs_badAddrsInd { get; set; }
		[DataMember]
		public Int64 mcs_bnftClaimId { get; set; }
		[DataMember]
		public bool mcs_bnftClaimIdSpecified { get; set; }
		[DataMember]
		public Int64 mcs_cancldByPtcpntId { get; set; }
		[DataMember]
		public bool mcs_cancldByPtcpntIdSpecified { get; set; }
		[DataMember]
		public string mcs_clmantAddrsOneTxt { get; set; }
		[DataMember]
		public string mcs_clmantAddrsTwoTxt { get; set; }
		[DataMember]
		public string mcs_clmantAddrsUnitNbr { get; set; }
		[DataMember]
		public string mcs_clmantCityNm { get; set; }
		[DataMember]
		public string mcs_clmantCntryNm { get; set; }
		[DataMember]
		public string mcs_clmantEmailAddrsTxt { get; set; }
		[DataMember]
		public string mcs_clmantFirstNm { get; set; }
		[DataMember]
		public string mcs_clmantLastNm { get; set; }
		[DataMember]
		public string mcs_clmantMiddleNm { get; set; }
		[DataMember]
		public string mcs_clmantPhoneAreaNbr { get; set; }
		[DataMember]
		public string mcs_clmantPhoneNbr { get; set; }
		[DataMember]
		public string mcs_clmantSsn { get; set; }
		[DataMember]
		public string mcs_clmantStateCd { get; set; }
		[DataMember]
		public string mcs_clmantZipCd { get; set; }
		[DataMember]
		public string mcs_cmpltdDt { get; set; }
		[DataMember]
		public bool mcs_cmpltdDtSpecified { get; set; }
		[DataMember]
		public Int64 mcs_creatdByPtcpntId { get; set; }
		[DataMember]
		public bool mcs_creatdByPtcpntIdSpecified { get; set; }
		[DataMember]
		public string mcs_createDt { get; set; }
		[DataMember]
		public bool mcs_createDtSpecified { get; set; }
		[DataMember]
		public string mcs_dupClosedInd { get; set; }
		[DataMember]
		public string mcs_everFiledInd { get; set; }
		[DataMember]
		public string mcs_exprtnDt { get; set; }
		[DataMember]
		public bool mcs_exprtnDtSpecified { get; set; }
		[DataMember]
		public string mcs_genderCd { get; set; }
		[DataMember]
		public string mcs_incompReasonTypeCd { get; set; }
		[DataMember]
		public Int64 mcs_intentToFileId { get; set; }
		[DataMember]
		public bool mcs_intentToFileIdSpecified { get; set; }
		[DataMember]
		public string mcs_itfCanctnReasonTypeNm { get; set; }
		[DataMember]
		public string mcs_itfStatusTypeCd { get; set; }
		[DataMember]
		public string mcs_itfTypeCd { get; set; }
		[DataMember]
		public string mcs_jrnDt { get; set; }
		[DataMember]
		public bool mcs_jrnDtSpecified { get; set; }
		[DataMember]
		public string mcs_jrnExtnlApplcnNm { get; set; }
		[DataMember]
		public string mcs_jrnExtnlKeyTxt { get; set; }
		[DataMember]
		public string mcs_jrnExtnlUserId { get; set; }
		[DataMember]
		public string mcs_jrnLctnId { get; set; }
		[DataMember]
		public string mcs_jrnObjId { get; set; }
		[DataMember]
		public string mcs_jrnStatusTypeCd { get; set; }
		[DataMember]
		public string mcs_jrnUserId { get; set; }
		[DataMember]
		public Int64 mcs_ptcpntClmantId { get; set; }
		[DataMember]
		public bool mcs_ptcpntClmantIdSpecified { get; set; }
		[DataMember]
		public Int64 mcs_ptcpntVetId { get; set; }
		[DataMember]
		public bool mcs_ptcpntVetIdSpecified { get; set; }
		[DataMember]
		public string mcs_rcvdDt { get; set; }
		[DataMember]
		public bool mcs_rcvdDtSpecified { get; set; }
		[DataMember]
		public string mcs_signedDt { get; set; }
		[DataMember]
		public bool mcs_signedDtSpecified { get; set; }
		[DataMember]
		public string mcs_signtrInd { get; set; }
		[DataMember]
		public string mcs_statusDt { get; set; }
		[DataMember]
		public bool mcs_statusDtSpecified { get; set; }
		[DataMember]
		public string mcs_submtdDt { get; set; }
		[DataMember]
		public bool mcs_submtdDtSpecified { get; set; }
		[DataMember]
		public string mcs_submtrApplcnTypeCd { get; set; }
		[DataMember]
		public Int64 mcs_submtrPtcpntId { get; set; }
		[DataMember]
		public bool mcs_submtrPtcpntIdSpecified { get; set; }
		[DataMember]
		public string mcs_supresLetterInd { get; set; }
		[DataMember]
		public string mcs_svcNbr { get; set; }
		[DataMember]
		public Int64 mcs_updatdByPtcpntId { get; set; }
		[DataMember]
		public bool mcs_updatdByPtcpntIdSpecified { get; set; }
		[DataMember]
		public string mcs_vetBrthdyDt { get; set; }
		[DataMember]
		public bool mcs_vetBrthdyDtSpecified { get; set; }
		[DataMember]
		public string mcs_vetFileNbr { get; set; }
		[DataMember]
		public string mcs_vetFirstNm { get; set; }
		[DataMember]
		public string mcs_vetLastNm { get; set; }
		[DataMember]
		public string mcs_vetMiddleNm { get; set; }
		[DataMember]
		public string mcs_vetSsnNbr { get; set; }
		[DataMember]
		public string mcs_vsoNm { get; set; }
	}
}