using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.TrackedItemService.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.TrackedItemService,findUnsolEvdnce method, Request.
	/// Code Generated by IMS on: 12/27/2018 4:24:21 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISfindUnsolEvdnceRequest : VEISEcRequestBase
	{
		[DataMember]
		public Guid RelatedParentId { get; set; }
		[DataMember]
		public string RelatedParentEntityName { get; set; }
		[DataMember]
		public string RelatedParentFieldName { get; set; }
		[DataMember]
		public bool LogTiming { get; set; }
		[DataMember]
		public bool LogSoap { get; set; }
		[DataMember]
		public bool Debug { get; set; }
		[DataMember]
		public LegacyHeaderInfo LegacyServiceHeaderInfo { get; set; }
		[DataMember]
		public string mcs_claiment_ptpcpnt_id { get; set; }
	}
}
