using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.AddressWebService.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.AddressWebService,findCityStateByPostalCode method, Response.
	/// Code Generated by IMS on: 1/3/2019 4:21:06 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISfcitystbpostfindCityStateByPostalCodeResponse : VEISEcResponseBase
	{
		[DataMember]
		public VEISfcitystbpostreturnMultipleResponse[] VEISfcitystbpostreturnInfo { get; set; }
	}
	[DataContract]
	public class VEISfcitystbpostreturnMultipleResponse
	{
		[DataMember]
		public string mcs_city { get; set; }
		[DataMember]
		public string mcs_cityType { get; set; }
		[DataMember]
		public string mcs_country { get; set; }
		[DataMember]
		public string mcs_postalCode { get; set; }
		[DataMember]
		public string mcs_processedBy { get; set; }
		[DataMember]
		public string mcs_stateProvince { get; set; }
		[DataMember]
		public string mcs_status { get; set; }
		[DataMember]
		public string mcs_statusCode { get; set; }
		[DataMember]
		public string mcs_statusDescription { get; set; }
	}
}
