using System;
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.AddressWebService.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.AddressWebService,vnAddressValidator method, Request.
	/// Code Generated by IMS on: 1/3/2019 4:28:22 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISfnaddvalvnAddressValidatorRequest : VEISEcRequestBase
	{
		[DataMember]
		public Guid RelatedParentId { get; set; }
		[DataMember]
		public string RelatedParentEntityName { get; set; }
		[DataMember]
		public string RelatedParentFieldName { get; set; }
		[DataMember]
		public bool LogTiming { get; set; }
		[DataMember]
		public bool LogSoap { get; set; }
		[DataMember]
		public bool Debug { get; set; }
		[DataMember]
		public LegacyHeaderInfo LegacyServiceHeaderInfo { get; set; }
		[DataMember]
		public string mcs_addressline1 { get; set; }
		[DataMember]
		public string mcs_addressline2 { get; set; }
		[DataMember]
		public string mcs_addressline3 { get; set; }
		[DataMember]
		public string mcs_city { get; set; }
		[DataMember]
		public string mcs_state { get; set; }
		[DataMember]
		public string mcs_postalcode { get; set; }
		[DataMember]
		public string mcs_mltypostaltypecd { get; set; }
		[DataMember]
		public string mcs_mltypostofficetypecd { get; set; }
	}
}
