using System; 
using System.Runtime.Serialization;
using VEIS.Core.Messages;

namespace VEIS.AppealService.Messages
{
	[DataContract]
	/// <summary>
	/// VEIS Enterprise Component for VEIS.AppealService,getAppeal method, Response.
	/// Code Generated by IMS on: 1/11/2019 8:08:47 PM
	/// Version: 2018.12.11.01
	/// </summary>
	/// <param name=none></param>
	/// <returns>none</returns>
	public class VEISgtaplgetAppealResponse : VEISEcResponseBase
	{
		[DataMember]
		public VEISgtaplGetAppealResponse VEISgtaplGetAppealResponseInfo { get; set; }
	}
	[DataContract]
	public class VEISgtaplGetAppealResponse
	{
		[DataMember]
		public VEISgtaplAppealRecord VEISgtaplAppealRecordInfo { get; set; }
	}
	[DataContract]
	public class VEISgtaplAppealRecord
	{
		[DataMember]
		public string mcs_AppealKey { get; set; }
		[DataMember]
		public string mcs_AppellantID { get; set; }
		[DataMember]
		public string mcs_AppealStatusCode { get; set; }
		[DataMember]
		public string mcs_AppealStatusDescription { get; set; }
		[DataMember]
		public DateTime mcs_BVAReceivedDate { get; set; }
		[DataMember]
		public bool mcs_BVAReceivedDateSpecified { get; set; }
		[DataMember]
		public string mcs_DocketNumber { get; set; }
		[DataMember]
		public DateTime mcs_DocketDate { get; set; }
		[DataMember]
		public bool mcs_DocketDateSpecified { get; set; }
		[DataMember]
		public DateTime mcs_DocketReceivedDate { get; set; }
		[DataMember]
		public bool mcs_DocketReceivedDateSpecified { get; set; }
		[DataMember]
		public string mcs_InsuranceOrLoanNumber { get; set; }
		[DataMember]
		public string mcs_MedicalFacilityCode { get; set; }
		[DataMember]
		public string mcs_MedicalFacilityName { get; set; }
		[DataMember]
		public string mcs_ActionTypeCode { get; set; }
		[DataMember]
		public string mcs_ActionTypeDescription { get; set; }
		[DataMember]
		public string mcs_AppealSubstitutionIndicator { get; set; }
		[DataMember]
		public DateTime mcs_DecisionReviewOfficerElectedDate { get; set; }
		[DataMember]
		public bool mcs_DecisionReviewOfficerElectedDateSpecified { get; set; }
		[DataMember]
		public string mcs_DecisionReviewOfficerId { get; set; }
		[DataMember]
		public string mcs_DecisionReviewOfficerReadyToRateIndicator { get; set; }
		[DataMember]
		public string mcs_CurrentFileStoredLocationCode { get; set; }
		[DataMember]
		public string mcs_CurrentFileStoredLocationDescription { get; set; }
		[DataMember]
		public string mcs_RegionalOfficeCode { get; set; }
		[DataMember]
		public string mcs_RegionalOfficeName { get; set; }
		[DataMember]
		public string mcs_ServiceOrganizationCode { get; set; }
		[DataMember]
		public string mcs_ServiceOrganizationDescription { get; set; }
		[DataMember]
		public string mcs_ServiceOrganizationName { get; set; }
		[DataMember]
		public DateTime mcs_ServiceOrganizationReceivedDate { get; set; }
		[DataMember]
		public bool mcs_ServiceOrganizationReceivedDateSpecified { get; set; }
		[DataMember]
		public string mcs_DecisionReviewOfficerPartialGrantOrDenialIndicator { get; set; }
		[DataMember]
		public string mcs_DecisionReviewOfficerInformalHearingIndicator { get; set; }
		[DataMember]
		public string mcs_DecisionReviewOfficerFormalHearingIndicator { get; set; }
		[DataMember]
		public string mcs_CaseStorageShelfLocationDescription { get; set; }
		[DataMember]
		public DateTime mcs_ChargeToCurrentLocationDate { get; set; }
		[DataMember]
		public bool mcs_ChargeToCurrentLocationDateSpecified { get; set; }
		[DataMember]
		public string mcs_StaffAttorneyId { get; set; }
		[DataMember]
		public VEISgtaplAppellant VEISgtaplAppellantInfo { get; set; }
		[DataMember]
		public VEISgtaplAppealVeteran VEISgtaplAppealVeteranInfo { get; set; }
		[DataMember]
		public VEISgtaplIssueMultipleResponse[] VEISgtaplIssueInfo { get; set; }
		[DataMember]
		public VEISgtaplDiaryMultipleResponse[] VEISgtaplDiaryInfo { get; set; }
		[DataMember]
		public VEISgtaplAppealDecision VEISgtaplAppealDecisionInfo { get; set; }
		[DataMember]
		public VEISgtaplAppealDateMultipleResponse[] VEISgtaplAppealDateInfo { get; set; }
		[DataMember]
		public VEISgtaplHearingRequestMultipleResponse[] VEISgtaplHearingRequestInfo { get; set; }
		[DataMember]
		public VEISgtaplRepFeesMultipleResponse[] VEISgtaplRepFeesInfo { get; set; }
	}
	[DataContract]
	public class VEISgtaplAppellant
	{
		[DataMember]
		public string mcs_AppellantRelationshipToVeteranCode { get; set; }
		[DataMember]
		public string mcs_AppellantRelationshipToVeteranDescription { get; set; }
		[DataMember]
		public string mcs_AppellantFirstName { get; set; }
		[DataMember]
		public string mcs_AppellantMiddleInitial { get; set; }
		[DataMember]
		public string mcs_AppellantLastName { get; set; }
		[DataMember]
		public string mcs_AppellantTitle { get; set; }
		[DataMember]
		public string mcs_AppellantNameSuffix { get; set; }
		[DataMember]
		public VEISgtaplAppellantAddress VEISgtaplAppellantAddressInfo { get; set; }
	}
	[DataContract]
	public class VEISgtaplAppellantAddress
	{
		[DataMember]
		public string mcs_AddressKey { get; set; }
		[DataMember]
		public string mcs_AppellantAddressLine1 { get; set; }
		[DataMember]
		public string mcs_AppellantAddressLine2 { get; set; }
		[DataMember]
		public string mcs_AppellantAddressCityName { get; set; }
		[DataMember]
		public string mcs_AppellantAddressStateCode { get; set; }
		[DataMember]
		public string mcs_AppellantAddressZipCode { get; set; }
		[DataMember]
		public string mcs_AppellantAddressCountryName { get; set; }
		[DataMember]
		public string mcs_AppellantAddressLastModifiedByROName { get; set; }
		[DataMember]
		public string mcs_AppellantAddressLastModifiedDate { get; set; }
		[DataMember]
		public string mcs_AppellantAddressNotes { get; set; }
		[DataMember]
		public string mcs_AppellantWorkPhoneNumber { get; set; }
		[DataMember]
		public string mcs_AppellantHomePhoneNumber { get; set; }
	}
	[DataContract]
	public class VEISgtaplAppealVeteran
	{
		[DataMember]
		public DateTime mcs_BirthDate { get; set; }
		[DataMember]
		public bool mcs_BirthDateSpecified { get; set; }
		[DataMember]
		public string mcs_VeteranFirstName { get; set; }
		[DataMember]
		public string mcs_VeteranMiddleInitial { get; set; }
		[DataMember]
		public string mcs_VeteranGender { get; set; }
		[DataMember]
		public string mcs_VeteranLastName { get; set; }
		[DataMember]
		public string mcs_VeteranSSN { get; set; }
		[DataMember]
		public DateTime mcs_FinalNoticeOfDeathDate { get; set; }
		[DataMember]
		public bool mcs_FinalNoticeOfDeathDateSpecified { get; set; }
	}
	[DataContract]
	public class VEISgtaplIssueMultipleResponse
	{
		[DataMember]
		public Int32 mcs_IssueSequenceNumber { get; set; }
		[DataMember]
		public string mcs_IssueProgramCode { get; set; }
		[DataMember]
		public string mcs_IssueProgramDescription { get; set; }
		[DataMember]
		public string mcs_IssueCode { get; set; }
		[DataMember]
		public string mcs_IssueCodeDescription { get; set; }
		[DataMember]
		public string mcs_IssueDescription { get; set; }
		[DataMember]
		public string mcs_IssueDispositionCode { get; set; }
		[DataMember]
		public string mcs_IssueDispositionDescription { get; set; }
		[DataMember]
		public DateTime mcs_IssueDispositionDate { get; set; }
		[DataMember]
		public bool mcs_IssueDispositionDateSpecified { get; set; }
		[DataMember]
		public string mcs_IssueLevel1Code { get; set; }
		[DataMember]
		public string mcs_IssueLevel1Description { get; set; }
		[DataMember]
		public string mcs_IssueLevel2Code { get; set; }
		[DataMember]
		public string mcs_IssueLevel2Description { get; set; }
		[DataMember]
		public string mcs_IssueLevel3Code { get; set; }
		[DataMember]
		public string mcs_IssueLevel3Description { get; set; }
		[DataMember]
		public string mcs_IssueNotes { get; set; }
		[DataMember]
		public VEISgtaplRemandReasonMultipleResponse[] VEISgtaplRemandReasonInfo { get; set; }
	}
	[DataContract]
	public class VEISgtaplRemandReasonMultipleResponse
	{
		[DataMember]
		public string mcs_RemandReasonCertifiedToBVAIndicator { get; set; }
		[DataMember]
		public Int32 mcs_RemandIssueSequenceNumber { get; set; }
		[DataMember]
		public bool mcs_RemandIssueSequenceNumberSpecified { get; set; }
		[DataMember]
		public string mcs_RemandReasonCode { get; set; }
		[DataMember]
		public string mcs_RemandReasonDescription { get; set; }
		[DataMember]
		public string mcs_LastModifiedByCode { get; set; }
		[DataMember]
		public string mcs_LastModifiedByName { get; set; }
		[DataMember]
		public string mcs_LastModifiedDate { get; set; }
	}
	[DataContract]
	public class VEISgtaplDiaryMultipleResponse
	{
		[DataMember]
		public string mcs_DiaryCode { get; set; }
		[DataMember]
		public string mcs_DiaryDescription { get; set; }
		[DataMember]
		public string mcs_AssignedStaffMemberName { get; set; }
		[DataMember]
		public DateTime mcs_AssignedToStaffMemberDate { get; set; }
		[DataMember]
		public bool mcs_AssignedToStaffMemberDateSpecified { get; set; }
		[DataMember]
		public Int32 mcs_DaysToCompleteDiaryItemQuantity { get; set; }
		[DataMember]
		public bool mcs_DaysToCompleteDiaryItemQuantitySpecified { get; set; }
		[DataMember]
		public DateTime mcs_DiarySuspenseDueDate { get; set; }
		[DataMember]
		public bool mcs_DiarySuspenseDueDateSpecified { get; set; }
		[DataMember]
		public DateTime mcs_DiaryClosedDate { get; set; }
		[DataMember]
		public bool mcs_DiaryClosedDateSpecified { get; set; }
		[DataMember]
		public string mcs_DiaryStatusCode { get; set; }
		[DataMember]
		public string mcs_DiaryStatusDescription { get; set; }
		[DataMember]
		public string mcs_BVAorRODiaryIndicatorText { get; set; }
		[DataMember]
		public string mcs_ResponseNotesDescription { get; set; }
		[DataMember]
		public string mcs_RequestedActivityDescription { get; set; }
	}
	[DataContract]
	public class VEISgtaplAppealDecision
	{
		[DataMember]
		public DateTime mcs_DecisionDate { get; set; }
		[DataMember]
		public bool mcs_DecisionDateSpecified { get; set; }
		[DataMember]
		public string mcs_DecisionDispositionCode { get; set; }
		[DataMember]
		public string mcs_DecisionDispositionDescription { get; set; }
		[DataMember]
		public string mcs_DecisionCitationNumber { get; set; }
		[DataMember]
		public string mcs_DecisionReviewOfficerDecisionIndicator { get; set; }
		[DataMember]
		public string mcs_DecisionReviewOfficerInformalHearingHeldIndicator { get; set; }
		[DataMember]
		public string mcs_DecisionReviewOfficerFormalHearingHeldIndicator { get; set; }
		[DataMember]
		public string mcs_DecisionRemandedToName { get; set; }
		[DataMember]
		public string mcs_DecisionTeamCode { get; set; }
		[DataMember]
		public string mcs_CounselId { get; set; }
		[DataMember]
		public string mcs_BoardMemberId { get; set; }
		[DataMember]
		public string mcs_HearingActionCode { get; set; }
		[DataMember]
		public string mcs_HearingActionDescription { get; set; }
		[DataMember]
		public string mcs_RegionalOfficeMailingStatusAction { get; set; }
		[DataMember]
		public DateTime mcs_RegionalOfficeMailingStatusDate { get; set; }
		[DataMember]
		public bool mcs_RegionalOfficeMailingStatusDateSpecified { get; set; }
		[DataMember]
		public string mcs_RemandedToCode { get; set; }
		[DataMember]
		public VEISgtaplSpecialContentionsMultipleResponse[] VEISgtaplSpecialContentionsInfo { get; set; }
	}
	[DataContract]
	public class VEISgtaplSpecialContentionsMultipleResponse
	{
		[DataMember]
		public string mcs_ContentionCode { get; set; }
		[DataMember]
		public string mcs_ContentionDescription { get; set; }
		[DataMember]
		public string mcs_ContentionIndicator { get; set; }
	}
	[DataContract]
	public class VEISgtaplAppealDateMultipleResponse
	{
		[DataMember]
		public string mcs_DateTypeCode { get; set; }
		[DataMember]
		public string mcs_DateTypeDescription { get; set; }
		[DataMember]
		public DateTime mcs_Date { get; set; }
		[DataMember]
		public bool mcs_DateSpecified { get; set; }
	}
	[DataContract]
	public class VEISgtaplHearingRequestMultipleResponse
	{
		[DataMember]
		public string mcs_HearingRequestedTypeCode { get; set; }
		[DataMember]
		public string mcs_HearingRequestedTypeDescription { get; set; }
		[DataMember]
		public DateTime mcs_HearingRequestRequestedDate { get; set; }
		[DataMember]
		public bool mcs_HearingRequestRequestedDateSpecified { get; set; }
		[DataMember]
		public DateTime mcs_HearingRequestScheduledDate { get; set; }
		[DataMember]
		public bool mcs_HearingRequestScheduledDateSpecified { get; set; }
		[DataMember]
		public string mcs_HearingRequestDispositionCode { get; set; }
		[DataMember]
		public string mcs_HearingRequestDispositionDescription { get; set; }
		[DataMember]
		public DateTime mcs_HearingRequestClosedDate { get; set; }
		[DataMember]
		public bool mcs_HearingRequestClosedDateSpecified { get; set; }
		[DataMember]
		public string mcs_BoardMemberId { get; set; }
		[DataMember]
		public string mcs_DecisionTeamCode { get; set; }
		[DataMember]
		public string mcs_HearingRequestNotes { get; set; }
	}
	[DataContract]
	public class VEISgtaplRepFeesMultipleResponse
	{
		[DataMember]
		public string mcs_LastName { get; set; }
		[DataMember]
		public string mcs_FirstName { get; set; }
		[DataMember]
		public string mcs_MiddleInitial { get; set; }
		[DataMember]
		public DateTime mcs_FeeDate { get; set; }
		[DataMember]
		public bool mcs_FeeDateSpecified { get; set; }
		[DataMember]
		public string mcs_DirectPay { get; set; }
		[DataMember]
		public DateTime mcs_BVAReceived { get; set; }
		[DataMember]
		public bool mcs_BVAReceivedSpecified { get; set; }
	}
}
