using System;
using System.ComponentModel.Composition;
using System.Runtime.Serialization;
using UDO.LOB.Core;
//using UDO.LOB.Extensions;
//using VEIS.Core.Messages;

//using Microsoft.Xrm.Sdk;
//using VRM.Integration.Servicebus.Core;

/// <summary>
/// VIMT LOB Component for UDOcreateUDOMilitaryTheater,createUDOMilitaryTheater method, Request.
/// Code Generated by IMS on: 6/26/2015 3:25:47 PM
/// Version: 2015.06.02
/// </summary>
/// <param name=none></param>
/// <returns>none</returns>

namespace UDO.LOB.MilitaryService.Messages
{
	//[Export(typeof(IMessageBase))]
	//[ExportMetadata("MessageType", MessageRegistry.UDOfindMilitaryServiceRequest)]
	[DataContract]
	public class UDOfindMilitaryServiceRequest : MessageBase
	{
		[DataMember]
		public string OrganizationName { get; set; }
		[DataMember]
		public Guid UserId { get; set; }
		//[DataMember]
		//public Guid RelatedParentId { get; set; }
		//[DataMember]
		//public string RelatedParentEntityName { get; set; }
		//[DataMember]
		//public string RelatedParentFieldName { get; set; }
		[DataMember]
		public bool LogTiming { get; set; }
		[DataMember]
		public bool LogSoap { get; set; }
		[DataMember]
		public bool Debug { get; set; }
		[DataMember]
		public UDOHeaderInfo LegacyServiceHeaderInfo { get; set; }
		[DataMember]
		public Guid udo_militaryserviceId { get; set; }
        [DataMember]
        public Guid ownerId { get; set; }
        [DataMember]
        public string ownerType { get; set; }
		[DataMember]
		public string ptcpntId { get; set; }
		[DataMember]
        public UDOcreateUDOMilitaryServiceRelatedEntitiesMultipleRequest[] UDOcreateUDOMilitaryServiceRelatedEntitiesInfo { get; set; }
	}
	[DataContract]
	public class UDOcreateUDOMilitaryServiceRelatedEntitiesMultipleRequest
	{
		[DataMember]
		public string RelatedEntityName { get; set; }
		[DataMember]
		public Guid RelatedEntityId { get; set; }
		[DataMember]
		public string RelatedEntityFieldName { get; set; }
	}
}
