using System;
using Microsoft.Xrm.Sdk;
using System.ComponentModel.Composition;
using System.Runtime.Serialization;
using VRM.Integration.Servicebus.Core;
using VRM.Integration.UDO.Messages;

/// <summary>
/// VIMT LOB Component for UDOcreateReceivables,createReceivables method, Response.
/// Code Generated by IMS on: 5/14/2015 8:09:04 AM
/// Version: 2015.05.05
/// </summary>
/// <param name=none></param>
/// <returns>none</returns>

namespace VRM.Integration.UDO.Awards.Messages
{
    [Export(typeof(IMessageBase))]
    [ExportMetadata("MessageType", MessageRegistry.UDOcreateReceivablesResponse)]
    [DataContract]
    public class UDOcreateReceivablesResponse : MessageBase
    {
        [DataMember]
        public bool ExceptionOccured { get; set; }
        [DataMember]
        public string ExceptionMessage { get; set; }
        [DataMember]
        public UDOcreateReceivablesMultipleResponse[] UDOcreateReceivablesInfo { get; set; }
    }
    [DataContract]
    public class UDOcreateReceivablesMultipleResponse
    {
        [DataMember]
        public Guid newUDOcreateReceivablesId { get; set; }
    }
}